### ISSUE TITLE
دیتاست tsetmc برای داده های بورس

### ISSUE THREAD

**Issue by amirshnll** [softwaretalks/newsletter#102]
##### نام و نام‌خانوادگی شما
userFullName: "امیر شکری"

##### عنوان مطلب (یا یک عنوان اختیاری بنویسید یا هم عنوان خود مقاله رو کپی کنید)
postTitle: "دیتاست رایگان شرکت مدیریت فناوری بورس تهران"

##### خلاصه‌ای حداکثر ۲ الی ۳ خطی درباره محتوای مقاله بنویسید.
postDescription: "احتمالا این روزها همه دیگه روزی چند بار اسم بورس رو شنیدیم و خب سرویس هایی که برای دسترسی به داده های بورس به صورت api موجود هست هم کم نیست ولی خب تا جایی که اطلاع دارم سرویس رایگانی پیدا نمیشه که برای پروژه های کوچولو و شخصی بشه استفاده کرد؛ سایت tsetmc یه ساختار آدرس خاص برای داده های هر سهام داره که به سادگی امکان دریافت دیتای لحظه ای رو دارید اما دقت کنید هر شرکتی دو کد برای ریکوئست زدن لازم داره که با توجه به زیاد بودن سهام ها نیاز هست یک لیست کامل رو داشته باشید که این دیتاست احتمالا کارتون رو راه بندازه"

##### لینک مطلب رو کامل وارد کنید.
postLink: "https://github.com/amirshnll/tsetmc-dataset/"

**Comment by Hameds** [comment]
@amirshnll ضمن تشکر، عنوان رو برای قرارگیری در خبرنامه کمی اصلاح کردم

**Comment by amirshnll** [comment]
> @amirshnll ضمن تشکر، عنوان رو برای قرارگیری در خبرنامه کمی اصلاح کردم

@Hameds تشکر
