### ISSUE TITLE
ربات تلگرامی برنامه کن!

### ISSUE THREAD

**Issue by anvaari** [softwaretalks/newsletter#105]
##### نام و نام‌خانوادگی شما
userFullName: "محمد عرب انواری"

##### عنوان مطلب (یا یک عنوان اختیاری بنویسید یا هم عنوان خود مقاله رو کپی کنید)
postTitle: "برنامه کن! یک ربات تلگرامی برای اضافه کردن رویدادها به تقویم گوگل"

##### خلاصه‌ای حداکثر ۲ الی ۳ خطی درباره محتوای مقاله بنویسید.
postDescription: "برنامه کن یک ربات تلگرامیه که آدما بتونن به راحتی ایونت هایی که میبینن (به خصوص توی تلگرام) رو به تقویم گوگلشون اضافه کنن. سورس این ربات به صورت آزاد منتشر شده و جا برای بهتر شدن زیاد داره.خوشحال میشم ادمای بیشتری ازش استفاده کنن و به دردشون بخوره."

##### لینک مطلب رو کامل وارد کنید.
postLink: "https://github.com/anvaari/BarnameKon"

**Comment by anvaari** [comment]
سلام و ممنون بابت زحماتتون برای این خبرنامه. راستش من اول دودل بودم که ایا گذاشتن لینک یک پروژه شخصی پذیرفته شدست برای خبرنامه یا که نه. با خوندن شرایط هم چیزی دستگیرم نشد. اگر با اهداف خبرنامه یکسو نیست این کار، لطفا اطلاع بدین. خیلی ممنونم

**Comment by Hameds** [comment]
@anvaari ممنونم از مشارکت شما. ایرادی در گذاشتن مطالب یا پروژه‌های شخصی نیست. یک پیش‌نویس اولیه از قوانین رو در آدرس زیر قرار دادیم که تا هفته آینده کاملش می‌کنیم تا قوانین مشارکت در محتوا شفاف‌تر باشند.

https://github.com/softwaretalks/newsletter/discussions/107
