### ISSUE TITLE
پیشنهاد ترجمه برای محتواهای انگلیسی

### ISSUE THREAD

**Issue by amirmojiry** [softwaretalks/newsletter#108]
شاید بد نباشه برای مطالبی که به زبان انگلیسی هستند، در ایشوها تگ «انگلیسی» (یا چنین چیزی) زد تا اگر کسی داوطلب بود، ترجمه‌اش کنه و توی خبرنامه علاوه بر لینک مطلب اصلی، لینک ترجمه‌اش هم بیاد.

**Comment by Hameds** [comment]
<div dir='rtl'>

پیشنهاد بسیار خوبی است. تنها نکته‌ای که الان به نظرم می‌رسه اینه که ما `Issue‍`هایی که ارسال می‌کنیم رو می‌بندیم و اینطوری فکر می‌کنم دنبال کردن اون تگ خاص محتوای قابل ترجمه هم مشکل می‌شه. پیشنهادی دارید؟

</div>

**Comment by amirbagh75** [comment]
فکر کنم منظورشون اینه قبل از ارسال این ترجمه صورت بگیره که لینک ترجمه هم  ضمیمه لینک اصلی بشه. البته اگر درست برداشت کرده باشم. در این صورت ایشو هنوز بازه و میشه پیگیریش کرد.

**Comment by amirmojiry** [comment]
<div dir="rtl">
خیلی ممنون از شما @Hameds که استقبال کردید. بله. منظور من همینی بود که @amirbagh75 گفتند.
اضافه کردن لینک ترجمه به لینک اصلی در خود ایمیل. با این حال چالش این کار اینه که مدت زمان کوتاهی برای ترجمه فرصت هست (کمتر از یک هفته).
اما اگر قرار نیست لینک ترجمه در ایمیل بیاد (و مثلن قراره توی آرشیو بیاد) ایده‌ی خاصی ندارم. چون مشکل بسته شدن ایشو به هر حال برقراره.
</div>

**Comment by amirbagh75** [comment]
این ایده خوبیه به نظرم ولی خب چون فعلا در محدوده کارها و کانتکست خبرنامه نیست ایشو رو میبندم.

**Comment by amirbagh75** [comment]
داخل یک ایشوی دیگه لیستی از ایده‌های جدیدی که میتونیم واسه خبرنامه در نظر بگیریم رو سرجمع میکنم و این مورد رو هم به اونجا اضافه میکنم. قراره مفهومی به نام شماره‌های ویژه درست کنیم که محتواهای دیگه‌ای هم علاوه بر خود خبرنامه داخل اون شماره‌ها قرار بدیم
