### ISSUE TITLE
باگ عدم بررسی اعتبار ایمیل در پاکت

### ISSUE THREAD

**Issue by amirbagh75** [softwaretalks/newsletter#109]
برای ارسال نیاز هست که مطمئن بشیم اعتبارمون از تعداد افرادی که میخوایم ارسال کنیم کمتر نباشه تا مشکل ناقص ارسال شدن پیش نیاد

**Comment by Hameds** [comment]
به نظرم با توجه به افزایش ظرفیت ارسال به ۱۵ هزار ایمیل در ماه فعلاً اجرای این ضرورتی نداره
