### ISSUE TITLE
لیست دروس مرتبط با اخلاق و تکنولوژی

### ISSUE THREAD

**Issue by royapakzad** [softwaretalks/newsletter#111]
##### نام و نام‌خانوادگی شما
userFullName: "رویا پاکزاد"

##### عنوان مطلب (یا یک عنوان اختیاری بنویسید یا هم عنوان خود مقاله رو کپی کنید)
postTitle: "لیست دروس مرتبط با اخلاق و تکنولوژی"

##### خلاصه‌ای حداکثر ۲ الی ۳ خطی درباره محتوای مقاله بنویسید.
postDescription: "به نظرتون لازمه که دانشجوهای مهندسی و علوم کامپیوتر هم کمی از علوم انسانی مثل فلسفه و اخلاق، مطالعات اجتماعی و حقوق بشر بخونن؟ تاثیرات اخلاقی و اجتماعی تکنولوژی به حدی واضح و مطرح شده که خیلی از دانشگاه‌ها شروع کردن به انطباق و ارایه‌ی درسهای علوم انسانی برای دانشجوهای مهندسی. این یه لیستیه از این کلاسا، منابع و ویدیوهای بعضی کلاسا هم موجوده."

##### لینک مطلب رو کامل وارد کنید.
postLink: "https://docs.google.com/spreadsheets/d/1jWIrA8jHz5fYAW4h9CkUD8gKS5V98PDJDymRf8d9vKI/edit#gid=0"

**Comment by amirbagh75** [comment]
مطلب جالب و متفاوتی میشه واسه خبرنامه بعدی! ممنون از شما
