### ISSUE TITLE
رفع یک باگ در فایرفاکس بعد از ۱۷ سال

### ISSUE THREAD

**Issue by hassan-shahbazi** [softwaretalks/newsletter#117]
##### نام و نام‌خانوادگی شما
userFullName: "حسن شهبازی"

##### عنوان مطلب (یا یک عنوان اختیاری بنویسید یا هم عنوان خود مقاله رو کپی کنید)
postTitle: "بسته شدن یک باگ در موزیلا فایرفاکس ۱۷ سال پس از اولین گزارش"

##### خلاصه‌ای حداکثر ۲ الی ۳ خطی درباره محتوای مقاله بنویسید.
postDescription: "این صفحه شامل مکالمات کاربران و توسعه دهندگان فایرفاکس است که نزدیک به ۱۷ سال طول کشیده است. خواندن این رشته مکالمات کمکی است به دریافتن نحوه گزارش، پیگیری، و نهایتا حل شدن یک باگ در نرم افزارهای متن باز."

##### لینک مطلب رو کامل وارد کنید.
postLink: "https://bugzilla.mozilla.org/show_bug.cgi?id=259640"

**Comment by amirbagh75** [comment]
چه عجیب!‌۱۷ سال.
