### ISSUE TITLE
ایراد فنی سال 2000

### ISSUE THREAD

**Issue by mayazdi** [softwaretalks/newsletter#148]
##### نام و نام‌خانوادگی شما
userFullName: "امین یزدی"

##### عنوان محتوا
postTitle: "ایراد فنی سال 2000"

##### خلاصه‌ای حداکثر ۲ الی ۳ خطی درباره مضمون محتوا
postDescription: "نمایش سال 2000 در سیستم‌های کامپیوتری مشکلاتی رو ایجاد می‌کرد. همچنین سال 1400 هم می‌تونه یه چنین مشکلاتی ایجاد کنه. به بهانه سال 1400 به این موضوع پرداخته شده."

##### لینک محتوا
postLink: "https://vrgl.ir/c1KsA"

**Comment by amirbagh75** [comment]
خود خبرنامه این باگ رو داره :)
