### ISSUE TITLE
راهکاری برای ولیدیشن فرمت ایشو‌ها در لحظه ایجاد

### ISSUE THREAD

**Issue by amirbagh75** [softwaretalks/newsletter#16]

**Comment by amirbagh75** [comment]
فکر میکنم بهترین راهکار این موضوع همون بات softwaretalks باشه که در گام اول فقط ولیدیشن yaml رو انجام بده و گزارش کارشو زیر ایشو برای کاربر بنویسه

**Comment by amirbagh75** [comment]
از milestone ها فعلا خارجش کردم تا بتونیم درباره نحوه عملکرد این موضوع به جمع‌بندی برسیم بعد ببینیم توی چه بازه‌ای میتونیم اضافه‌اش کنیم.

**Comment by amirbagh75** [comment]
<div dir='rtl'>

برای شما مقدوره که یک بات با اسم مثلا softwaretalksbot ایجاد کنید؟ که وظیفه بررسی لینک‌ها و صحت فایل yml رو به اون بسپریم.
</div>

**Comment by amirbagh75** [comment]
<div dir='rtl'>
البته گمان کنم نیازی نباشه میتونیم با همین باته کار کنیم. بررسی میکنم مجدد کامنت میزارم اینجا که راه‌حل نهاییم چی شده @Hameds 
https://github.com/marketplace/actions/create-or-update-comment

</div>

**Comment by Hameds** [comment]
> برای شما @Hameds مقدوره که یک بات با اسم مثلا softwaretalksbot ایجاد کنید؟ که وظیفه بررسی لینک‌ها و صحت فایل yml رو به اون بسپریم.

مشکلی نیست هر زمان نیاز بود در خدمتم

**Comment by amirbagh75** [comment]
نیازی به ایجاد ساختار خودکار برای این موضوع نمیبینم. موقع ارسال تستی مشخص میشه اگر مشکلی وجود داشته باشه و همون‌ موقع میشه راحت رفعش کرد. پس نیاز به وقت گذاشتن برای این مورد نمیبینم. ایشو رو میبندم.
