### ISSUE TITLE
چجوری فرانت اند دولوپر وب بشیم؟ (رودمپ برنامه نویسی فرانت اند)

### ISSUE THREAD

**Issue by ashkanRmk** [softwaretalks/newsletter#166]
##### نام و نام‌خانوادگی شما
userFullName: "اشکان رحمانی"

##### عنوان محتوا
postTitle: "چجوری فرانت اند دولوپر وب بشیم؟ (رودمپ برنامه نویسی فرانت اند)"

##### خلاصه‌ای حداکثر ۲ الی ۳ خطی درباره مضمون محتوا
postDescription: "در این ویدیو، نقشه راه (رودمپ) برنامه‌نویسی فرانت‌اند توضیح داده میشه.
یعنی اینکه از ابتدا چه چیزهایی رو برای برنامه نویسی فرانت اند Front end باید یاد بگیرین تا وارد مسیر این حوزه برنامه نویسی بشین و بدونین که چه زمانی آماده ورود به بازار کار به عنوان یک فرانت‌اند دولوپر هستین."

##### لینک محتوا
postLink: "https://youtu.be/Gi9Q7UwWwqc"

**Comment by amirbagh75** [comment]
اشکان جان من یک ویرایش کوچیک کردم متن رو جاهایی که به نظرم نیم‌فاصله نیاز بود یا کلمه "را" به کار نرفته بود اضافه کردم.

**Comment by ashkanRmk** [comment]
اوکیه امیر جان
