### ISSUE TITLE
ریدایرکت شدن لینک‌ها، لایسنس

### ISSUE THREAD

**Issue by alefvanoon** [softwaretalks/newsletter#168]
سلام، آیا امکان این هست که لینک‌ها به صورت مستقیم قرار بگیرند؟
چون ریدارکت شدنشون جالب نیست و به نظرم مناسب هم نباشه.
در مورد لایسنس‌ نمی‌خواید تصمیمی بگیرید؟

**Comment by Hameds** [comment]
در مورد ریدارکت شدن ظاهراً این بخشی از مکانیزم سرویس‌دهنده ایمیل است و مطمئن نیستم کنترلی روش داریم یا خیر. چک می‌کنم و اگر امکان لینک مستقیم بود ازش استفاده می‌کنیم.

در مورد لایسنس منظورتون درباره لایسنس همین مخزنه؟

**Comment by alefvanoon** [comment]
> در مورد ریدارکت شدن ظاهراً این بخشی از مکانیزم سرویس‌دهنده ایمیل است و مطمئن نیستم کنترلی روش داریم یا خیر. چک می‌کنم و اگر امکان لینک مستقیم بود ازش استفاده می‌کنیم.

خیلی ممنون!

> در مورد لایسنس منظورتون درباره لایسنس همین مخزنه؟

بله منظورم همین‌ مخزنه.

**Comment by amirbagh75** [comment]
فکر نکنم سرویس ایمیلی که استفاده میشه امکان لینک مستقیم بده. چون همه آمارها و کلیک‌ها رو بر اساس همین لینک‌های غیرمستقیم میاره.

**Comment by Hameds** [comment]
@amirbagh75 برای اطمینان از دوستان در پاکت هم سوال می‌کنم

**Comment by amirbagh75** [comment]
اگر نتیجه‌ای حاصل نشد ایشو رو ببندم @Hameds
