### ISSUE TITLE
راهنمای خرید کیبورد مکانیکی برای مبتدیان

### ISSUE THREAD

**Issue by hassan-shahbazi** [softwaretalks/newsletter#186]
##### نام و نام‌خانوادگی شما
userFullName: "حسن شهبازی"

##### عنوان محتوا
postTitle: "راهنمای خرید کیبورد مکانیکی برای مبتدیان"

##### خلاصه‌ای حداکثر ۲ الی ۳ خطی درباره مضمون محتوا
postDescription: "در این پست، نویسنده به معرفی کیبورد‌های مکانیکی پرداخته، و سپس با بررسی فاکتورهای موجود، انواع آن را معرفی می‌کند."

##### لینک محتوا
postLink: "https://coolgadget.substack.com/p/beginners-guide-to-mechanical-keyboards"

**Comment by amirbagh75** [comment]
من همین الان داشتم اماده میشدم با یک روز تاخیر خبرنامه رو ارسال کنم. یک دفعه دیدم پست جدید اومده.

**Comment by hassan-shahbazi** [comment]
من فکر میکنم کل پروسه اتوماتیک باشه، فقط لیبیل ها رو دستی میزنی

**Comment by amirbagh75** [comment]
نه هنوز ارسال دستیه. البته ارسال کردن فقط با فشردن دکمه توی صفحه اکشن‌هاست که خیلی با اتومات فرق نداره ولی خب متاسفانه هنوز توی تنبلی از ماشین‌ها عقب‌تریم
