### ISSUE TITLE
مولتی تسکینگ میتواند به سلامت و عملکرد شما آسیب جدی وارد کند.

### ISSUE THREAD

**Issue by hassan-shahbazi** [softwaretalks/newsletter#191]
##### نام و نام‌خانوادگی شما
userFullName: "حسن شهبازی"

##### عنوان محتوا
postTitle: "چرا افراد موفق مولتی تسک نیستند."

##### خلاصه‌ای حداکثر ۲ الی ۳ خطی درباره مضمون محتوا
postDescription: "در این پست نویسنده با اشاره به تحقیقات صورت گرفته در دانشگاه استنفورد نشان میدهد چگونه انجام دادن همزمان تسک های زیاد باعث آسیب در عملکرد و حتی آسیب جسمی و مغزی میشود."

##### لینک محتوا
postLink: "https://www.linkedin.com/pulse/why-successful-people-dont-multitask-dr-travis-bradberry/"

**Comment by amirbagh75** [comment]
سلام جناب شهبازی عزیز
من اتفاقی وبلاگ شما رو خوندم و متوجه شدم شما روی کرنل لینوکس زمان گذاشتین و تجربیاتی کسب کردین.
من در حال حاضر راهبر مشهد‌لاگ (گروه کاربران لینوکس مشهد)‌ هستم و میخواستم برای جلسه بعدی لاگ برنامه ریزی کنم. 
به ذهنم رسید که بتونیم از تجربیات شما استفاده کنیم و برامون توی لاگ از کرنل لینوکس بگید 😅
اگر تمایل دارین یک راه ارتباطی بگین که من باهاتون خیلی کوتاه بتونم صحبت کنم.
@hassan-shahbazi

**Comment by hassan-shahbazi** [comment]
ممنونم امیر عزیز
به ایمیلی که توی پروفایل گیت‌هابت هست پیام دادم

**Comment by amirbagh75** [comment]
به به دم شما گرم. چشم الان بررسی میکنم
