### ISSUE TITLE
فروپاشی خط زمان: در مورد فیلم تنت

### ISSUE THREAD

**Issue by mojtaba-yekta** [softwaretalks/newsletter#200]
##### نام و نام‌خانوادگی شما
userFullName: "مجتبی یکتا"

##### عنوان محتوا
postTitle: "فروپاشی خط زمان: در مورد فیلم تنت"

##### خلاصه‌ای حداکثر ۲ الی ۳ خطی درباره مضمون محتوا
postDescription: "شروع فیلم تنت در حقیقت در میانه‌ی آن است آنجا که سیتور به دنبال قطعه نهایی از یک الگوریتم فیزیکی است تا با آن آنتروپی جهان را معکوس کند و این معکوس شدن در نهایت منجر به نابودی دنیا خواهد شد."

##### لینک محتوا
postLink: "https://vrgl.ir/r11Bq"

**Comment by Hameds** [comment]
ضمن تشکر، این خبرنامه در حوزه توسعه نرم‌افزار است و این محتوا ارتباطی با موضوع آن ندارد
