### ISSUE TITLE
تفاوت بین Process و Thread چیست؟

### ISSUE THREAD

**Issue by mokarchi** [softwaretalks/newsletter#207]
##### نام و نام‌خانوادگی شما
userFullName: "Amir Mokarchi"

##### عنوان محتوا
postTitle: "تفاوت بین Process و Thread چیست؟"

##### خلاصه‌ای حداکثر ۲ الی ۳ خطی درباره مضمون محتوا
postDescription: " فرآیندها برای دستیابی به اجرای برنامه ها به صورت همزمان و متوالی استفاده می شوند. در حالی که thread یک واحد اجرایی برنامه است که از محیط فرآیند استفاده می کند. سیستم عامل از این واقعیت برای کاهش سربار و بهبود محاسبات استفاده می کند."

##### لینک محتوا
postLink: "https://vrgl.ir/WEbBp"

**Comment by Hameds** [comment]
ضمن تشکر در مورد چند پست مرتبط با این پیشنهاد بنده این است که همه این موارد رو در قالب یک نوشته با جزئیات و همچنین نمونه کدی که روی گیت‌هاب از یک مثال واقعی باشه منتشر کنید. مهم نیست ترجمه باشه یا نوشته خود شما. دنبال کردن نوشته‌های کوتاه توضیحی به این شکل کمی دشواره.
