### ISSUE TITLE
تفاوت بین Asynchronous و Multi-Threading

### ISSUE THREAD

**Issue by mokarchi** [softwaretalks/newsletter#208]
##### نام و نام‌خانوادگی شما
userFullName: "Amir Mokarchi"

##### عنوان محتوا
postTitle: "تفاوت بین Asynchronous و Multi-Threading"

##### خلاصه‌ای حداکثر ۲ الی ۳ خطی درباره مضمون محتوا
postDescription: "    انتخاب بین دو مدل برنامه‌نویسی به طور عمده به performance بستگی دارد."

##### لینک محتوا
postLink: "https://vrgl.ir/zetYG"

**Comment by Hameds** [comment]
ضمن تشکر در #207 پیشنهادی در این خصوص مطرح شد
