### ISSUE TITLE
پیاده سازی Asynchronous به صورت Multi-Threaded

### ISSUE THREAD

**Issue by mokarchi** [softwaretalks/newsletter#209]
##### نام و نام‌خانوادگی شما
userFullName: "Amir Mokarchi"

##### عنوان محتوا
postTitle: "پیاده سازی Asynchronous به صورت Multi-Threaded"

##### خلاصه‌ای حداکثر ۲ الی ۳ خطی درباره مضمون محتوا
postDescription: "پیاده سازی با طعم آشپزی"

##### لینک محتوا
postLink: "https://vrgl.ir/W9hjh"

**Comment by Hameds** [comment]
ضمن تشکر در #207 پیشنهادی در این خصوص مطرح شد
