### ISSUE TITLE
تفاوت بین Task و Thread

### ISSUE THREAD

**Issue by mokarchi** [softwaretalks/newsletter#210]
##### نام و نام‌خانوادگی شما
userFullName: "Amir Mokarchi"

##### عنوان محتوا
postTitle: "تفاوت بین Task و Thread"

##### خلاصه‌ای حداکثر ۲ الی ۳ خطی درباره مضمون محتوا
postDescription: "کلاس Thread برای ایجاد و دستکاری کردن یک Thread در ویندوز استفاده می شود در حالی که یک Task نمایانگر برخی از عملیات های asynchronous و بخشی از Task Parallel Programming یا به اختصار TPL می باشد "

##### لینک محتوا
postLink: "https://vrgl.ir/u6pJe"

**Comment by Hameds** [comment]
ضمن تشکر در #207 پیشنهادی در این خصوص مطرح شد
