### ISSUE TITLE
عنوان مطلب | ترجیحا فارسی

### ISSUE THREAD

**Issue by SadeghEidi** [softwaretalks/newsletter#217]
##### نام و نام‌خانوادگی شما
userFullName: "صادق عیدی"

##### عنوان محتوا
postTitle: ""

##### خلاصه‌ای حداکثر ۲ الی ۳ خطی درباره مضمون محتوا
postDescription: ""

##### لینک محتوا
postLink: ""

**Comment by amirbagh75** [comment]
صادق چی شده؟ @SadeghEidi

**Comment by Hameds** [comment]
فکر می‌کنم برای تست ارسال شده بنابراین این رو می‌بندم
