### ISSUE TITLE
بررسی هدرهای امنیتی وب سایت شما

### ISSUE THREAD

**Issue by Hameds** [softwaretalks/newsletter#219]
##### نام و نام‌خانوادگی شما
userFullName: "حامد سعیدی"

##### عنوان محتوا
postTitle: "بررسی هدرهای امنیتی وب سایت شما"

##### خلاصه‌ای حداکثر ۲ الی ۳ خطی درباره مضمون محتوا
postDescription: "به کمک این وب سایت می‌توانید وضعیت هدرهای امنیتی وب سایت مورد نظرتان را بررسی کنید. این سرویس، سایت شما را بر اساس هدرهای موجود رتبه‌بندی می‌کند و می‌توانید ببینید چه هدرهایی را فراموش کردید."

##### لینک محتوا
postLink: "https://securityheaders.com/"

**Comment by amirbagh75** [comment]
حامد‌جان یک سوالی برای من پیش اومد. من تا الان خودم هرچی محتوا میفرستادم رو خودم هم تایید میکردم که به نظر کار نامعقولیه. گمون کنم نیازه محتواهایی که خودم میفرستم رو کسی جز خودم تایید کنه طبق قوانین

**Comment by Hameds** [comment]
@amirbagh75 باید تعداد تایید کننده‌های محتوا رو بیشتر کنیم

**Comment by amirbagh75** [comment]
پس بهتره شیوه‌نامه‌ای برای افرادی که علاقه دارند در تایید کمک کنند تهیه کنم
