### ISSUE TITLE
جعبه‌ابزارهایی برای طراحی و پیاده‌سازی مدل‌های یادگیری ماشین — شفاف‌تر، مسئولانه‌تر و توضیح‌پذیرتر

### ISSUE THREAD

**Issue by royapakzad** [softwaretalks/newsletter#227]
##### نام و نام‌خانوادگی شما
userFullName: "رویا پاکزاد"

##### عنوان محتوا
postTitle: "جعبه‌ابزارهایی برای طراحی و پیاده‌سازی مدل‌های یادگیری ماشین — شفاف‌تر، مسئولانه‌تر و توضیح‌پذیرتر"

##### خلاصه‌ای حداکثر ۲ الی ۳ خطی درباره مضمون محتوا
postDescription: "اگر اخبار مربوط به سیاست‌گذاری‌های فناوری رو دنبال می‌کنید، حتما متوجه شدید که صحبت از سوگیری و تبعیض در یادگیری ماشین، بحث جمع‌آوری داده و حقوق کاربران ، شفافیت، توضیح‌پذیری و مستند‌سازی و غیره خیلی زیاد شده. این لیست شامل جعبه‌ابزارهاییه که کمک میکنه مدل‌های یادگیری ماشین‌تون رو بررسی کنید؛ تو مستندسازی‌تون شفاف‌تر باشید؛ داده‌هاتون رو با رعایت حفظ حریم خصوصی جمع‌آوری و نگهداری کنید و یا حتی از خودتون بپرسید که با در نظر گرفتن تاثیرات اجتماعی، اصلا مسئولانه هست که این محصول رو وارد بازار کنید؟! "

##### لینک محتوا
postLink: "https://github.com/users/royapakzad/projects/3"

**Comment by amirbagh75** [comment]
سلام خانم پاکزاد. یک مدت نبودین دلمون برای مطالب جالب و متفاوت‌تون تنگ شده بود 👋 
ممنون از انتشار این لیست ارزشمند 👌

**Comment by royapakzad** [comment]
قربان شما، لطف دارید 🙏
