### ISSUE TITLE
ویرایش توضیحِ مخزن

### ISSUE THREAD

**Issue by kokabi1365** [softwaretalks/newsletter#234]
<div dir="rtl">
تصحیحِ بخشِ About مخزن:

«خبرنامه‌ای تخصصی برایِ مهندسانِ نرم‌افزار و گیک‌هایِ کامپیوتر»
</div>

**Comment by ohmydevops** [comment]
<div dir='rtl'>

ممنون ایوب عزیز. اصلاحش کردم. راستی برای راست به چپ شدن بخش about ایده‌ای داری آيا؟

</div>

**Comment by kokabi1365** [comment]
<div dir="rtl">
یه راهِ شلخته‌ش اینه که توضیح رو یه‌خطی کنی و آخرِ جمله چندتا کاراکترِ نادیدنی (مثلاً ALt + 0160) بذاری تا متنِ هل داده بشه سمتِ راست. 
<br><br>
واقعاً جایِ تأسفه همچین سرویس‌هایِ بزرگی با وجودِ داشتنِ حجمِ زیادی از کاربرانِ راست‌به‌چپ‌زبان پاسخی به حداقلِ نیازهایِ اون‌ها نمی‌دن. پیچیدگی فنی هم نداره. الان Sublime چند ساله علی‌رغمِ درخواستِ زیادِ کاربران، پشتیبانی از زبانِ فارسی رو به ادیتورش اضافه نمی‌کنه. همینطور پلتفرمِ آموزشِ زبانِ Duolingo که حتی جواب درخواست‌ها رو نمی‌ده. آدم زورش می‌آد که حتی پاسخی به درخواست‌ها نمی‌دن. 
<br><br>
آرزو می‌کنم کشورِ عزیزم ایران روزی به جایگاهی برسه که امثال گیتهاب و پی‌پال برای خدمات‌رسانی به ما ناز نکنن؛ التماس کنن. متأسفانه بشر با وجودِ پیشرفت‌هایِ عظیمِ علمی همچنان در بحثِ اخلاق و روابطِ انسانی از قانونِ جنگل پیروی می‌کنه.
<br><br>
سیاسی حماسی شد 😀 
</div>

**Comment by ohmydevops** [comment]
<div dir='rtl'>

فکر خوبیه، الان یک‌خطی کردمش.
درباره موضوع پشتیبانی نشدن هم با شما هم‌نظر هستم. البته شاید ما از این زاویه به قضیه نگاه میکنیم ولی برای اون‌ها و کمپانی‌ها بحث سود‌آوری و ارزش داشتن انجام همچین‌ کاری مطرح باشه. درسته که پیاده‌سازی راست به چپ و نمایش صحیحش خیلی کار خاصی نمیخواد، ولی خب احتمالا همچین چرخه‌ای رو طی میکنه و ریجکت میشه.

</div>

**Comment by kokabi1365** [comment]
<div dir="rtl">
موضوع فراتر از این حرف‌هاست.
</div>
