### ISSUE TITLE
منتشر شد: Flysystem v2

### ISSUE THREAD

**Issue by mrmmg** [softwaretalks/newsletter#25]
##### نام و نام‌خانوادگی شما
userFullName: "محمد مهدی غلامرضایی"

##### لینک مطلب رو کامل وارد کنید.
postLink: "https://laravel-news.com/flysystem-v2"

##### عنوان مطلب (یا یک عنوان اختیاری بنویسید یا هم عنوان خود مقاله رو کپی کنید)
postTitle: "منتشر شد: Flysystem v2"

##### خلاصه‌ای حداکثر ۲ الی ۳ خطی درباره محتوای مقاله بنویسید.
postDescription: "فلای سیستم یک کتابخانه جامع برای زبان php است که با استفاده از آن می توانیم برای فضاهای ذخیره سازی مختلفی همچون دیسک لوکال، گوگل درایو، آمازون، دراپ باکس و... از آن استفاده کنیم. این کتابخانه در نسخه دوم خود موارد جدیدی همچون Exceptionها را اضافه کرده است."

**Comment by amirbagh75** [comment]
سلام و متشکر از شما
توی بخش توضیحات مطلب یک غلط املایی (ای -> این) وجود داره و جمله بخش اول هم ناقص تموم شده که نیازه یک ادیت کوچیک بزنین.

**Comment by mrmmg** [comment]
> سلام و متشکر از شما
> توی بخش توضیحات مطلب یک غلط املایی (ای -> این) وجود داره و جمله بخش اول توی توضیحات هم ناقص تموم شده که نیازه یک ادیت کوچیک بزنین.

با سلام و احترام انجام شد
یک پیشنهاد اینکه فضای گیت هاب برای تایپ فارسی اصلا مناسب نیست و چون قواعد راست به چپ رعایت نشده و هنگام تایپ خصوصا اگر در وسط جمله کلمه انگلیسی باشد کلا همه چیز بهم میریزد
اگر این مورد را رفع بفرمایید ممنون میشوم

**Comment by amirbagh75** [comment]
فکر کنم راه‌حل‌های مشکلی که گفتید این‌ها باشه:

- نوشتن مطلب در یک ادیتور با ساپورت از rtl، مثلا من توی لینوکس از gedit استفاده میکنم.
- پیدا کردن یک افزونه مرورگر برای نوشتن متون فارسی بدون دردسر در گیتهاب در بخش issue ها
- و اگر این افزونه جایی نوشته نشده بود خودمون درستش کنیم.

سعی میکنم به این موضوع فکر کنم و ببینم چه کارهایی میشه براش انجام داد تا این مشکل که شما گفتین حل بشه

**Comment by Hameds** [comment]
<div dir='rtl'>

@mrmmg 
متاسفانه ادیتور github به صورت پیش‌فرض امکان راست به چپ رو پشتیبانی نمی‌کنه اما اگر متن خودتون رو بین یک `div` به شکل زیر قرار بدین راست به چپ می‌شه مثل متن همین کامنتی که مشاهده می‌کنید


@amirbagh75 
اگر متن‌ها اینطوری راست به چپ بشن (یعنی یک div اضافه بشه) مشکلی برای پارس کردن issueها ایجاد نمی‌شه؟
</div>

 `<div dir="rtl">متن شما</div>`

**Comment by amirbagh75** [comment]
الان در حال بررسی هستم
