### ISSUE TITLE
آیا کدها و برنامه نویسی امکان تاخیر آلزایمر را دارند؟

### ISSUE THREAD

**Issue by amirshnll** [softwaretalks/newsletter#254]
##### نام و نام‌خانوادگی شما
userFullName: "امیر شکری"

##### عنوان محتوا
postTitle: "آیا کدها و برنامه نویسی امکان تاخیر آلزایمر را دارند؟"

##### خلاصه‌ای حداکثر ۲ الی ۳ خطی درباره مضمون محتوا
postDescription: "در این نوشته در مورد اینکه برنامه نویسی و کدها امکان تاخیر در بیماری آلزایمر را دارند صحبت شده که خیلی جالب میتونه باشه..."

##### لینک محتوا
postLink: "https://www.vice.com/en/article/qkv5xq/can-learning-to-code-delay-alzheimers"

**Comment by Foroozani** [comment]
that was intresting
