### ISSUE TITLE
چگونه می توان سیستمی را طراحی کرد که برای 100 میلیون کاربر جوابگو باشد

### ISSUE THREAD

**Issue by rashid2003** [softwaretalks/newsletter#259]
##### نام و نام‌خانوادگی شما
userFullName: "راشد عبیدی"

##### عنوان محتوا
postTitle: "چگونه میتوان سیستمی را طراحی کرد که برای 100 میلیون کاربر جوابگو باشد"

##### خلاصه‌ای حداکثر ۲ الی ۳ خطی درباره مضمون محتوا
postDescription: "طراحی سیستمی که از صدها میلیون کاربر پشتیبانی کند کار آسانی نیست. این همیشه یک چالش بزرگ برای یک معمار نرم‌افزار است. در این نوشته خواهید خواند که چگونه میشود به سادگی از ۱۰۰ میلیون کاربر پذیرایی کرد"

##### لینک محتوا
postLink: "https://levelup.gitconnected.com/how-to-design-a-system-to-scale-to-your-first-100-million-users-4450a2f9703d"

**Comment by ohmydevops** [comment]
سلام جناب عبیدی. آیا این لینک که ارسال کردید با توضیحات‌تون همخوانی دارد؟ گمان من بر این هست که لینک اشتباهی هست چون نتونستم بین توضیحات و مقاله ارتباطی پیدا بکنم. یک بررسی بفرمایید

**Comment by rashid2003** [comment]
معذرت
من در حال تهیه لیستی بودم از مقالات به همین دلیل این لینک رو اشتباهی فرستادم

لینک ذیل لینک درست هست:
https://levelup.gitconnected.com/how-to-design-a-system-to-scale-to-your-first-100-million-users-4450a2f9703d

**Comment by ohmydevops** [comment]
ممنونم ازت راشد عزیز
