### ISSUE TITLE
بررسی روش‌های مختلف ذخیره اطلاعات در مرورگر کاربر

### ISSUE THREAD

**Issue by vghaderi** [softwaretalks/newsletter#26]
##### نام و نام‌خانوادگی شما
userFullName: "وحید قادری"

##### لینک مطلب رو کامل وارد کنید.
postLink: "https://blog.bitsrc.io/browser-storage-options-and-their-state-in-2021-6808b949087a"

##### عنوان مطلب (یا یک عنوان اختیاری بنویسید یا هم عنوان خود مقاله رو کپی کنید)
postTitle: "روش‌های مختلف ذخیره اطلاعات در مرورگر کاربر و وضعیت آن‌ها در ۲۰۲۱"

##### خلاصه‌ای حداکثر ۲ الی ۳ خطی درباره محتوای مقاله بنویسید.
postDescription: "نویسنده در این مقاله انواع روش‌های ذخیره اطلاعات در مرورگرهای مدرن و ویژگی‌ها و محدودیت‌های‌شان را بررسی کرده است. از روش‌های ساده‌تر Local Storage و Session Storage تا روش‌های پیشرفته‌تر IndexedDB و Cookies در این مقاله بررسی شده‌اند و مرجع مناسبی برای انتخاب یکی از این روش‌ها در شرایط ویژه پروژه و چالش‌های پیش روی‌تان است."

**Comment by Hameds** [comment]
<div dir='rtl'>

لطفاً عنوان تمام انگلیسی رو تا جایی که می‌شه ترجمه کنید. همچنین لطفاً توضیح بیشتری بنویسید که خواننده موقع دیدن لینک در ایمیل با خوندن خلاصه متوجه بشه لینک براش مناسبه یا نه و ترغیب به کلیک بشه.

</div>

**Comment by vghaderi** [comment]
> لطفاً عنوان تمام انگلیسی رو تا جایی که می‌شه ترجمه کنید. همچنین لطفاً توضیح بیشتری بنویسید که خواننده موقع دیدن لینک در ایمیل با خوندن خلاصه متوجه بشه لینک براش مناسبه یا نه و ترغیب به کلیک بشه.

ویرایش کردم
