### ISSUE TITLE
خواندن هر کتابی چقدر زمان می‌بره؟

### ISSUE THREAD

**Issue by Rahmanism** [softwaretalks/newsletter#274]
##### نام و نام‌خانوادگی شما
userFullName: "Rahmanism"

##### عنوان محتوا
postTitle: "خواندن هر کتابی چقدر زمان می‌بره؟"

##### خلاصه‌ای حداکثر ۲ الی ۳ خطی درباره مضمون محتوا
postDescription: "قبل از این که هر کتابی را بخونید از طریق سایت How long to read از تخمین زمان خوندن اون کتاب مطلع بشید.    
همچنین بهتون اجازه می‌ده قسمتی از کتاب رو بخونید تا با سرعت خوندن خودتون زمان کتاب رو تخمین بزنه.  
"

##### لینک محتوا
postLink: "https://howlongtoread.com/"

**Comment by ohmydevops** [comment]
سلام وقت شما بخیر

توی متن بخش توضیحات نیازی به آوردن مجدد لینک نیست و بهتره فقط توضیحات باشه و لینک رو در همون بخش مربوطه‌اش قرار میدیم.

**Comment by Rahmanism** [comment]
> سلام وقت شما بخیر
> 
> توی متن بخش توضیحات نیازی به آوردن مجدد لینک نیست و بهتره فقط توضیحات باشه و لینک رو در همون بخش مربوطه‌اش قرار میدیم.

ادیتش کردم.
