### ISSUE TITLE
سرویس پایتون Flask در محیط عملیاتی (Production)

### ISSUE THREAD

**Issue by afzouni** [softwaretalks/newsletter#28]
##### نام و نام‌خانوادگی شما
userFullName: "سیدمصطفی افزونی"

##### لینک مطلب رو کامل وارد کنید.
postLink: "https://vrgl.ir/Yw37Q"

##### عنوان مطلب (یا یک عنوان اختیاری بنویسید یا هم عنوان خود مقاله رو کپی کنید)
postTitle: "سرویس پایتون Flask در محیط عملیاتی (Production)"

##### خلاصه‌ای حداکثر ۲ الی ۳ خطی درباره محتوای مقاله بنویسید.
postDescription: "فلسک یا Flask یکی از کتابخانه‌های پایتون برای پیاده‌سازی وب‌سرویس و API است که بعنوان یک میکروفریمورک ساده اما سبک محسوب می‌شود.

در این نوشتار به چگونگی استفاده از Flask در محیط Production (محیط عملیاتی یا محصول) با استفاده از Reverse Proxy و gunicorn (بعنوان WSGI) و بصورت یک سرویس لینوکسی پرداخته شده است."

**Comment by afzouni** [comment]
اگر بخاطر راست‌به‌چپ مشکل داره، کلا فارسی استفاده کنم. داخل ایمیل‌های ارسالی نمیدونم چجوری میشه

**Comment by amirbagh75** [comment]
منم که قالبو طراحی کردم نمیدونم چطوری میشه باید تست کنم :)
ولی همه چیز رو فکر کنم rtl کردم که کار معقولی نیست و باید auto کنم با این حساب. من تست میکنم و نتیجه رو برای شما این‌جا میزارم تا به نتیجه درست برسیم

**Comment by afzouni** [comment]
مرسیی
