### ISSUE TITLE
آموزش کوبرنتیز به زبان ساده

### ISSUE THREAD

**Issue by mthri** [softwaretalks/newsletter#284]
##### نام و نام‌خانوادگی شما
userFullName: "امیرمهدی مطهری"

##### عنوان محتوا
postTitle: "آموزش کوبرنتیز به زبان ساده"

##### خلاصه‌ای حداکثر ۲ الی ۳ خطی درباره مضمون محتوا
postDescription: ""

##### لینک محتوا
postLink: "https://bostandoust.ir/kubernetes/"

**Comment by ohmydevops** [comment]
سلام امیرجان
مطلبت توضیحات نداره گویا. یک خلاصه توضیح بزار
