### ISSUE TITLE
چطور برای خرید به یک وب سایت یا پیج اینستاگرامی اعتماد کنیم؟

### ISSUE THREAD

**Issue by alireza95jalili** [softwaretalks/newsletter#297]
##### نام و نام‌خانوادگی شما
userFullName: "علیرضا جلیلی"

##### عنوان محتوا
postTitle: "چطور برای خرید به یک وب سایت یا پیج اینستاگرامی اعتماد کنیم؟"

##### خلاصه‌ای حداکثر ۲ الی ۳ خطی درباره مضمون محتوا
postDescription: "چطور میشه فهمید یک وب‌سایت یا پیج اینستگرامی معتبره یا نه؟ خدمات پس از فروش خوبی دارند؟ چیزی که میفرستن همونیه که عکسش رو گذاشتند؟ یا کلاه برداریه و پولمون رو بالا میکشن؟
اگر تا حالا با این سوالات مواجه شدید، خوندن این مقاله خیلی کمکتون می‌کنه."

##### لینک محتوا
postLink: "https://vrgl.ir/gyG1k"

**Comment by Hameds** [comment]
ضمن تشکر این مقاله خیلی عمومی است و برای خبرنامه تخصصی مهندسی نرم‌افزار مناسب نیست
