### ISSUE TITLE
دانشنامه ای آزاد برای بررسی سانسور اینترنت (فیلتر و تحریم)

### ISSUE THREAD

**Issue by xhdix** [softwaretalks/newsletter#298]
##### نام و نام‌خانوادگی شما
userFullName: "سید حسین درواری"

##### عنوان محتوا
postTitle: "دانشنامه ای آزاد برای بررسی سانسور اینترنت (فیلتر و تحریم)"

##### خلاصه‌ای حداکثر ۲ الی ۳ خطی درباره مضمون محتوا
postDescription: "دانشنامه ای آزاد و در حال توسعه برای بررسی تخصصی سانسور اینترنت که در آن می توانید بیاموزد چطور فیلترینگ و تحریم را با دانش و یا بدون دانش تخصصی تشخیص دهید. مطلب های منتشر شده تاکنون: الف)آموزش ساده تا پیشرفته ی OONI. ب)سانسور در ارتباط DNS. ج)سانسور در لایه‌ی شبکه و انتقال. د)سانسور در لایه‌ی کاربرد."

##### لینک محتوا
postLink: "https://wikicensorship.github.io/fa/docs/measure-internet-censorship/"

**Comment by ohmydevops** [comment]
محتوایی ارزشمند در وب فارسی. ممنون

**Comment by xhdix** [comment]
<div dir="rtl">

لطف دارید. باعث افتخار هست. :heart: 
</div>
