### ISSUE TITLE
راهنمای رعایت حقوق دیجیتال کاربران برای شرکت‌های فناوری: شفافیت و پاسخگویی

### ISSUE THREAD

**Issue by royapakzad** [softwaretalks/newsletter#300]
##### نام و نام‌خانوادگی شما
userFullName: "رویا پاکزاد"

##### عنوان محتوا
postTitle: "راهنمای رعایت حقوق دیجیتال کاربران برای شرکت‌های فناوری: شفافیت و پاسخگویی"

##### خلاصه‌ای حداکثر ۲ الی ۳ خطی درباره مضمون محتوا
postDescription: "با وجود همه‌ی نگرانی‌ها در مورد اینترنت در ایران، هنوز هم راه‌هایی هست که شرکت‌های نوپا تا جایی که میتونن به حقوق کاربرانشون احترام بذارن و شفافیت و پاسخگویی رو سرلوحه‌ی کارشون قرار بدن. این پست شامل توصیه‌ها و دفترچه‌ی راهنماییه که بر اساس شاخص رتبه‌بندی حقوق دیجیتال نوشته شده. 
"

##### لینک محتوا
postLink: "https://vrgl.ir/1zeST"

**Comment by royapakzad** [comment]
@ohmydevops شرمنده دیر فرستادم، شاید به خبرنامه‌ی این هفته نرسه که اشکالی نداره. ممنون از خبرنامه‌ی خوبتون

**Comment by ohmydevops** [comment]
ممنون از شما. من امروز تعطیل هستم و بررسی کردم.
