### ISSUE TITLE
ترجمه فارسی کتاب هنر کد خوانا

### ISSUE THREAD

**Issue by Hameds** [softwaretalks/newsletter#305]
##### نام و نام‌خانوادگی شما
userFullName: "حامد سعیدی"

##### عنوان محتوا
postTitle: "ترجمه فارسی کتاب هنر کد خوانا"

##### خلاصه‌ای حداکثر ۲ الی ۳ خطی درباره مضمون محتوا
postDescription: "این ترجمه کتاب The Art Of Readable Code است که در دو قالب PDF و Markdown در مخزن گیت‌هابی قرار داده شده است."

##### لینک محتوا
postLink: "https://github.com/Hossein52Hz/The-Art-Of-Readable-Code-Persian"

**Comment by meiadnoushadi** [comment]
thanks for this book 👌🏻👌🏻👌🏻
