### ISSUE TITLE
تغییر To به BCC در ارسال خبرنامه

### ISSUE THREAD

**Issue by Hameds** [softwaretalks/newsletter#31]
کل ایمیل‌ها در BCC قرار گیرند

**Comment by afzouni** [comment]
ایمیل محدودیت تعداد ارسال نداره؟ از ابزارهای مثل 
mailchimp 
نمیشه استفاده کرد؟

**Comment by amirbagh75** [comment]
در حال حاضر، پاکت اسپانسر ایمیل سرور شده و محدودیت خاصی نداریم به اون معنا.

**Comment by Hameds** [comment]
<div dir='rtl'>

@amirbagh75 در کل از امکان ارسال ایمیل Transactional در پاکت استفاده کنیم می‌شه با فراخوانی تک به تک ایمیل فرستاد 
یا ارسال لیستی رو استفاده کنیم (API پاکت رو بررسی می‌کنم)

</div>

**Comment by amirbagh75** [comment]
> @amirbagh75 در کل از امکان ارسال ایمیل Transactional در پاکت استفاده کنیم می‌شه با فراخوانی تک به تک ایمیل فرستاد
> یا ارسال لیستی رو استفاده کنیم (API پاکت رو بررسی می‌کنم)

فکر کنم خیلی کند بشه این چون عملا باید برای هر یوزر یک درخواست smtp بدیم به گمانم. وقتی لیستی باشه خوبیش اینه یکبار BCC میکنیم. ولی خب بازم تست کنیم شاید من اشتباه فکر میکنم.
