### ISSUE TITLE
یادآور تعداد فوتی های کرونا در شماره ی جدید

### ISSUE THREAD

**Issue by amirshnll** [softwaretalks/newsletter#319]
<div dir="rtl">

سلام امیدوارم که کسی هیچ کدوم از اعضای خانوادش رو بخاطر کرونا از دست نده  با توجه به اینکه فوتی های کرونا روز به روز داره بیشتر میشه با صحبت هایی که با @ohmydevops  کردم به نظرم این شماره یک یادآور در فوتر برای این موضوع در نظر گرفته باشه یا مثلا بکگراند خبرنامه به مشکی تغییر بکنه

<br />

issue ایجاد کردم که این موضوع بین دوستان مختلف به همه پرسی گذاشته باشه

<br />

@Hameds

</div>

**Comment by ohmydevops** [comment]
<div dir='rtl'>
من موافق این موضوع هستم که شماره این هفته رو، به احترام کشته‌شدگان ویروس کرونا مشکی کنیم تا یادآوری باشه برای تلاش بیشتر جمعی در مقابله با کرونا
</div>

**Comment by Hameds** [comment]
من هم موافق هستم. امیدوارم همه سلامت باشند. اگر کمکی برای این مساله از من ساخته است (برای کد) بفرمایید

**Comment by ohmydevops** [comment]
سلام وقت بخیر
من این هفته‌ها به خاطر مشغله کاری زیاد فرصت نکردم روی طراحی کار کنم. اگر برای هفته آتی کسی تمایل داره کمک کنه بگه وگرنه من برنامه‌ریزی کنم که زمانی رو اختصاص بدم

**Comment by amirshnll** [comment]
> سلام وقت بخیر
> من این هفته‌ها به خاطر مشغله کاری زیاد فرصت نکردم روی طراحی کار کنم. اگر برای هفته آتی کسی تمایل داره کمک کنه بگه وگرنه من برنامه‌ریزی کنم که زمانی رو اختصاص بدم

@ohmydevops 

please check #322

**Comment by ohmydevops** [comment]
بسیار عالی. من شب برسم منزل بررسی میکنم و خبرنامه این هفته رو امشب ارسال میکنم با تم جدید
