### ISSUE TITLE
تولید اتوماتیک آرشیو خبرنامه‌ها

### ISSUE THREAD

**Issue by Hameds** [softwaretalks/newsletter#34]
<div dir='rtl'>

از روی خبرنامه تولیدی یک نسخه html ایجاد بشه که روی سایت خبرنامه در بخش آرشیو نمایش داده بشه. تا زمان ایجاد این قابلیت می‌شه به صورت دستی این فایل‌ها رو push کرد

</div>

**Comment by amirbagh75** [comment]
من امشب سعی میکنم لابه‌لای کارهام نسخه‌های قبل رو دستی اضافه کنم

**Comment by amirbagh75** [comment]
تقریبا اکثرشونو اکی کردم. برنچ جدید میارم اینجا تست میگیرم و سپس مرج میکنم و خبرشو توی توییتر میزارم میتونیم به بچه‌ها خبر بدیم بعدش و لینکشو هم در اختیارشون بزاریم @Hameds

**Comment by amirbagh75** [comment]
تمام آرشیو‌ها تا این لحظه اضافه شد به سایت
https://newsletter.softwaretalks.ir/#archive

**Comment by amirbagh75** [comment]
برای آرشیو از خروجی تمپلیت انجین استفاده کنم راحت‌ترم. موقع پیاده‌سازی حواسم به این نکته باشه

**Comment by amirbagh75** [comment]
این موضوع واقعا مهمه من هی تنبلیم میشه آپدیت کنم آرشیو رو !

**Comment by amirbagh75** [comment]
در اولین فرصت اتوماتش میکنم که راحت بشیم

**Comment by amirbagh75** [comment]
<div dir='rtl'>
امروز سعی میکنم روی این موضوع کار کنم که فقط فایل html رو با نام صحیح در پوشه ارشیو push کنه. بقیه چیزهاش رو راحت میشه دستی انجام داد
</div>
