### ISSUE TITLE
تغییر زمان خبرنامه به دو هفته یکبار

### ISSUE THREAD

**Issue by ohmydevops** [softwaretalks/newsletter#346]
<div dir='rtl'>
تهیه محتوای خوب کاری دشوار میباشد. بهتره که بعد از این مدت زمان خبرنامه رو به ۲ هفته تغییر بدیم تا بتونیم محتوای بهتری (و احتمالا بیشتر در هر شماره) رو تامین کنیم. 

همچنین نیازمند برنامه‌ای برای جذب محتوا از طرف جامعه نرم‌افزاری هستیم.
</div>

**Comment by Hameds** [comment]
> بسیار خب. من فعلا برای هفته گذشته ارسال نکردم پس همین پنج‌شنبه شماره بعدی رو ارسال میکنیم و تا اخر ابان فعلا هر هفته میفرستیم تا بعد برنامه‌ریزی جدیدی بکنیم.

اینجا توضیحات بیشتری نوشتم https://github.com/softwaretalks/newsletter/discussions/355
