### ISSUE TITLE
«چگونه مغز خودم را فریب دادم تا کارهای سخت را دوست داشته باشد»

### ISSUE THREAD

**Issue by mvahedii** [softwaretalks/newsletter#361]
##### نام و نام‌خانوادگی شما
userFullName: "Mohammad Vahedi"

##### عنوان محتوا
postTitle: "«چگونه مغز خودم را فریب دادم تا کارهای سخت را دوست داشته باشد»"

##### خلاصه‌ای حداکثر ۲ الی ۳ خطی درباره مضمون محتوا
postDescription: "ما احتمالا با بازی‌های کامپیوتری و یا جست و جو در فضاهای مجازی در تلفن‌های همراهمان مشکلی نداشته باشیم. در واقع، ما می‌توانیم جلوی صفحه نمایش بنشینیم و هر دو این فعالیت‌ها را به مدت دو ساعت یا حتی بیشتر بدون اینکه تمرکزمان از بین برود انجام دهیم.
اما نیم‌ساعت مطالعه درسی چطور؟ یا حتی یک ساعت کسب و کار؟"

##### لینک محتوا
postLink: "https://vrgl.ir/bUdTi"

**Comment by ohmydevops** [comment]
ممنون از شما
دقیقا نمیدونم آیا میتونم بین این مطلب و موضوعات تخصصی مهندسی‌نرم‌افزار ارتباطی پیدا بکنم یا نه. برای همین فعلا این هفته توی لیست مطالب قرارش نمیدم تا بتونم بیشتر فکر کنم.
نظر شما چیه @Hameds  ?

**Comment by Hameds** [comment]
<div dir='rtl'>

ممنونم از @mvahedii بابت اشتراک این لینک. همانطور که @ohmydevops هم اشاره کرد در خبرنامه softwaretalks درباره موضوعات تخصصی مهندسی نرم‌افزار صحبت می‌شه و موضوع لینک شده بر این اساس off topic است و بنابراین این issue رو می‌بندم.

</div>
