### ISSUE TITLE
Build your own (insert technology here)

### ISSUE THREAD

**Issue by mvahedii** [softwaretalks/newsletter#362]
##### نام و نام‌خانوادگی شما
userFullName: "Mohammad Vahedi"

##### عنوان محتوا
postTitle: "Build your own (insert technology here)"

##### خلاصه‌ای حداکثر ۲ الی ۳ خطی درباره مضمون محتوا
postDescription: "همیشه بهترین راه برای فهمیدن عمیق یک ابزار اینه که بدونیم اون ابزار چطوری ساخته شده. با کمک این ریپو در هر زبان، فریمورک و یا ابزاری که کار می کنید میتونید عمیق بشید."

##### لینک محتوا
postLink: "https://github.com/danistefanovic/build-your-own-x"

**Comment by ohmydevops** [comment]
این مطلب فوق‌العاده بود. ممنون از معرفیش
