### ISSUE TITLE
اجازه گرفتن از کاربر بابت رصد شدن با یاندکس‌متریکا

### ISSUE THREAD

**Issue by ohmydevops** [softwaretalks/newsletter#369]
https://yandex.com/support/metrica/general/notification.html#notification

**Comment by Hameds** [comment]
درباره این موضوع بیشتر توضیح می‌دی امیرحسین عزیز؟

**Comment by ohmydevops** [comment]
یک ابزاری بود شبیه گوگل انالتیکز که کمک میکنه ببینیم افراد چطوری سایت اصلی ما رو پیدا میکنن و این جور چیزا
به صورت تستی اضافه کردم و اکی بود. میخوام امروز یک مدال اضافه کنم که اگر کاربر تمایل داشت کوکی‌های این شکلی براش ایجاد بشه وگرنه که هیچی

**Comment by ohmydevops** [comment]
https://termly.io/resources/articles/gdpr-cookie-consent-examples/

**Comment by ohmydevops** [comment]
اضافه شد
