### ISSUE TITLE
ارسال خودکار خبرنامه به وسیله گیتهاب‌ اکشن‌ها

### ISSUE THREAD

**Issue by amirbagh75** [softwaretalks/newsletter#37]
خبرنامه‌ در روزهای پنج‌شنبه به صورت خودکار راس ساعت مشخصی ایمیل شود. همچنین یک نسخه از خبرنامه قبل از ارسال اصلی، به صورت خودکار به لیست تست ایمیل شود. ارسال تستی ساعت ۹ صبح پنج‌شنبه و ارسال اصلی ساعت ۹ شب پنج‌شنبه انجام شود.

**Comment by amirbagh75** [comment]
Run your GitHub Actions workflow on a schedule:
https://jasonet.co/posts/scheduled-actions/

**Comment by amirbagh75** [comment]
برای ساعات ارسال تست و غیرتست خبرنامه نظر شما چیه؟ البته فکر کنم بشه بعدا این مورد رو به نظرسنجی گذاشت ولی فعلا باید یک ساعت مشخص انتخاب کنیم
@Hameds

**Comment by Hameds** [comment]
<div dir='rtl'>

@amirbagh75 به نظر من نیازی نیست که در یک زمان برنامه‌ریزی شده انجام بشه. می‌شه گیت‌هاب اکشن رو تعریف کرد و به صورت دستی اجراش کرد. یعنی اینطوری که یک گیت‌هاب اکشن برای ارسال تست و یک گیت‌‌هاب اکشن برای ارسال نهایی. با اجرای این اکشن از روی گیت‌هاب، کار ارسال انجام بشه و ایشوهای ارسال شده هم اتوماتیک بسته بشن. این یک مرحله جلوتر از اجرای دستی فعلی است و احتمالاً زمان کمتری می‌بره. شاید حتی تا مدت‌ها نیاز نشه که schedule برای اجرای این اکشن‌ها داشته باشیم و همین شیوه کفایت کنه

</div>
