### ISSUE TITLE
با این اسکریپت نیازی به پوشه وصایای امام ندارید !

### ISSUE THREAD

**Issue by dozheiny** [softwaretalks/newsletter#377]
##### نام و نام‌خانوادگی شما
userFullName: "ایلیا آقامجیدی"

##### عنوان محتوا
postTitle: "با این اسکریپت نیازی به پوشه وصایای امام ندارید !" 

##### خلاصه‌ای حداکثر ۲ الی ۳ خطی درباره مضمون محتوا
postDescription: "اومدیم یه کاری کردیم که دیگه نیازی نباشه به اینکه نگران باشین اگه مامان باباتون فایل های شخصی تون رو پیدا کردن اونا رو توی کلی فولدر مخفی کنین"

##### لینک محتوا
postLink: "https://vrgl.ir/DS2qf"

**Comment by ohmydevops** [comment]
عجب :))

**Comment by dozheiny** [comment]
:))))))
کار خفنی نیست . ولی مرسی لینکمو گذاشتین
