### ISSUE TITLE
شخم توییتر فارسی (اراضی برنامه نویسان)

### ISSUE THREAD

**Issue by vahidbaghi** [softwaretalks/newsletter#389]
##### نام و نام‌خانوادگی شما
userFullName: "وحید باقی"

##### عنوان محتوا
postTitle: "شخم توییتر فارسی (اراضی برنامه نویسان)"

##### خلاصه‌ای حداکثر ۲ الی ۳ خطی درباره مضمون محتوا
postDescription: "در این مطلب به تحلیل و بررسی توییت های «لیستی از اهالی فارسی‌زبان آی‌تی توییتر» پرداخته می‌شود و قصد داریم ببینیم برنامه ‌نویسان در توییتر مشغول چه کاری هستند؟!"

##### لینک محتوا
postLink: "https://vrgl.ir/KdKMG"

**Comment by ohmydevops** [comment]
به به چه جالبه
