### ISSUE TITLE
اضافه کردن دکمه حمایت مالی

### ISSUE THREAD

**Issue by Hameds** [softwaretalks/newsletter#391]
اسکریپت پی‌پینگ برای حمایت مالی

```
<script
     src="https://cdn.payping.ir/statics/donate.min.js"
     type="text/javascript"
     charset="utf-8"
     pp-userName="hamedblog"
     pp-description="با حمایت مالی، به تداوم پروژه کمک کنید :)"
     pp-amounts="20000,50000,100000"
     pp-avatar="https://nocdn.payping.ir/files/186124/profilepic/855fe932-0e02-400c-a961-5cf51af6d8ad.jpg"
></script>

```

**Comment by ohmydevops** [comment]
حامد جان این نسخه نهاییه؟ چون یک طوریه رفتارش. البته همه چیزش درسته. اون موردی که مشکل داره به نظرم رو اسکرین شات میزارم

**Comment by ohmydevops** [comment]
این input ها چرا سفیدن و هیچ متن توضیحی نداره که دقیقا هر کدوم برای چیه؟


![image](https://user-images.githubusercontent.com/21690865/146982038-b3551e43-cd2e-43d3-bffb-8a6e9ffe44b9.png)

**Comment by ohmydevops** [comment]
@Hameds

**Comment by Hameds** [comment]
توی پیش‌نمایشی که به من نشون می‌ده به نظر مرتب میاد. باز هم چک می‌کنم. گزینه‌های زیادی برای سفارشی کردن نداره و صرفا می‌شه همین مبالغ پیش‌فرض رو اضافه کرد و توضیح کلی که بالا نمایش داده می‌شه
