### ISSUE TITLE
طراحی قالب خبرنامه ایمیلی؟

### ISSUE THREAD

**Issue by amirbagh75** [softwaretalks/newsletter#4]
برای طراحی قالب خبرنامه میتونیم از امکانات پاکت استفاده کنیم یا مستقل از اون پیش بریم؟ @Hameds 

نظر من روی مستقل بودن هستش

**Comment by Hameds** [comment]
من تازه درخواست فعال‌سازی حساب رو روی پاکت فرستادم. به محض آماده شدن اطلاع میدم که بعد از مقایسه تصمیم بگیریم

**Comment by amirbagh75** [comment]
آیا نتیجه‌ای حاصل شد که بتونیم مقایسه کنیم؟‌ @Hameds

**Comment by Hameds** [comment]
@amirbagh75 کار رو با MailChimp یا سرویس رایگان دیگه پیش ببرید. پاکت هنوز پاسخی دریافت نکردم

**Comment by amirbagh75** [comment]
ممنونم. پس با MailChimp بریم جلو. صفحه ثبت‌نام هم میشه با MailChimp ساخت. فعلا فقط مقوله مشارکت رو با گیت‌هاب پیش خواهیم برد + ارسال های هفتگی

**Comment by amirbagh75** [comment]
از تمپلیت‌های آماده MailChimp استفاده خواهیم کرد. فقط ترتمیز و مناسب فارسی بشه. اگر هم چیز خوبی پیدا نشد از همون تمپلیتی که خودم درست کردم استفاده میکنم و بهبودش میدم.

**Comment by amirbagh75** [comment]
هر وقت نهایی شد تصمیم این ایشو رو میبندم

**Comment by amirbagh75** [comment]
اگر پاکت جوابی دادن تا آخر هفته میشه از ا‌ون‌ها استفاده کرد. اگر هم نه که هیچی دیگه ما همه چیز رو با همون MailChimp پیش میبریم. فعلا فرض رو این گذاشتم که پاکت جواب نمیده یا دیر جواب میده و با MailChimp دارم میرم جلو @Hameds

**Comment by amirbagh75** [comment]
آیا پاکت بهمون تمپلیت ایمیل هم میده؟ توی سایت چیزی نتونستم پیدا کنم.
 @Hameds

**Comment by amirbagh75** [comment]
بنا شد از قالب خودمون استفاده کنیم. توی ریپو قرارش میدم. این ایشو رو هم میبندم
