### ISSUE TITLE
ایراد در شماره عنوان ایمیل خبرنامه

### ISSUE THREAD

**Issue by Hameds** [softwaretalks/newsletter#402]
شماره‌ای که در عنوان ایمیل خبرنامه درج می‌شود به نظر اشتباهی یک شماره به عقب برگشته است

**Comment by ohmydevops** [comment]
سلام. متوجه مشکل نمیشم. چطور به عقب برگشته؟ الان ۴۳ هستیم

**Comment by ohmydevops** [comment]
حامد جان متوجه این مشکل نشدم هنوز. @Hameds

**Comment by Hameds** [comment]
@ohmydevops 

از روی اینباکس یا لاگ پاکت (در بخش Email( یک بررسی داشته باش. اگر اشتباه نکنم از چند شماره قبل یکی به عقب برگشته بود
