### ISSUE TITLE
با این دانش‌ها می‌توانید از آمازون پیشنهاد شغلی فرانت بگیرید

### ISSUE THREAD

**Issue by amirshnll** [softwaretalks/newsletter#418]
##### نام و نام‌خانوادگی شما
userFullName: "امیر شکری"

##### عنوان محتوا
postTitle: "با این دانش‌ها می‌توانید از آمازون پیشنهاد شغلی فرانت بگیرید"

##### خلاصه‌ای حداکثر ۲ الی ۳ خطی درباره مضمون محتوا
postDescription: "اگر در فرآیند مصاحبه به عنوان فرانت اند دولوپر هستید کافیه این cheatsheet رو مطالعه کنید و دانشتون رو برای کار با شرکت های بزرگتر تطبیق بدین"

##### لینک محتوا
postLink: "https://medium.com/itnext/frontend-interview-cheatsheet-that-helped-me-to-get-offer-on-amazon-and-linkedin-cba9584e33c7"

**Comment by Hameds** [comment]
ضمن تشکر، فقط typo در عنوان اصلاح شد.
