### ISSUE TITLE
کارهای جالبی که با github.dev می‌توان انجام داد

### ISSUE THREAD

**Issue by Hameds** [softwaretalks/newsletter#436]
##### نام و نام‌خانوادگی شما
userFullName: "حامد سعیدی"

##### عنوان محتوا
postTitle: "کارهای جالبی که با github.dev می‌توان انجام داد"

##### خلاصه‌ای حداکثر ۲ الی ۳ خطی درباره مضمون محتوا
postDescription: "در این مقاله ۱۰ کاری که مستقیم یا به کمک اکستنشن‌ها می‌توان با نسخه تحت وب ادیتور گیت‌هاب انجام داد معرفی شده است."

##### لینک محتوا
postLink: "https://dev.to/lostintangent/10-awesome-things-you-can-do-with-github-dev-5fm"

**Comment by SinaKarimi7** [comment]
@Hameds There is an error in the above article link. The page returned 404 error.

Here is the correct link to your article:
"https://dev.to/lostintangent/10-awesome-things-you-can-do-with-github-dev-5fm7"

**Comment by SinaKarimi7** [comment]
> ##### نام و نام‌خانوادگی شما
> userFullName: "حامد سعیدی"
> 
> ##### عنوان محتوا
> postTitle: "کارهای جالبی که با github.dev می‌توان انجام داد"
> 
> ##### خلاصه‌ای حداکثر ۲ الی ۳ خطی درباره مضمون محتوا
> postDescription: "در این مقاله ۱۰ کاری که مستقیم یا به کمک اکستنشن‌ها می‌توان با نسخه تحت وب ادیتور گیت‌هاب انجام داد معرفی شده است."
> 
> ##### لینک محتوا
> postLink: "https://dev.to/lostintangent/10-awesome-things-you-can-do-with-github-dev-5fm"

@Hameds There is an error in the above article link. The page returned 404 error.

Here is the correct link to your article:
"https://dev.to/lostintangent/10-awesome-things-you-can-do-with-github-dev-5fm7"
