### ISSUE TITLE
پردازش تصویر، اساس جلوه‌های ویژه در سینما

### ISSUE THREAD

**Issue by ohmydevops** [softwaretalks/newsletter#447]
##### نام و نام‌خانوادگی شما
userFullName: "امیرحسین بقایی"

##### عنوان محتوا
postTitle: "پردازش تصویر، اساس جلوه‌های ویژه در سینما"

##### خلاصه‌ای حداکثر ۲ الی ۳ خطی درباره مضمون محتوا
postDescription: "حتما همه شما جلوه‌های ویژه رو در فیلم‌ها و تبلیغات تلویزیونی و اینترنتی دیدین، اما سوال اصلی این هست که این جلوه‌های ویژه یا همون VFX چطوری ساخته و پردازش میشن و به فیلم ها اضافه میشن؟ یکی از علومی که اساس جلوه‌های ویژه رو تشکیل میده، علم پردازش تصویره. اما شاید براتون سوال بشه که دقیقا پردازش تصویر چطوری به جلوه‌های ویژه کمک میکنه. توی این ویدیو جذاب و کوتاه با کارهای پایه در جلوه‌های ویژه آشنا میشید"

##### لینک محتوا
postLink: "https://youtu.be/gYu4esqvnQ0"

**Comment by Hameds** [comment]
امیرحسین عزیز این مطلب به خبرنامه این هفته نرسید. من برای هفته آینده چک می‌کنم قبلش که ایشو تگ نخورده محتوا نداشته باشیم

**Comment by ohmydevops** [comment]
هیچ اشکال نداره.
