### ISSUE TITLE
دنیای قبل و بعد از دیپ لرنینگ

### ISSUE THREAD

**Issue by amirshnll** [softwaretalks/newsletter#457]
##### نام و نام‌خانوادگی شما
userFullName: "امیر شکری"

##### عنوان محتوا
postTitle: "دنیای قبل و بعد از دیپ لرنینگ"

##### خلاصه‌ای حداکثر ۲ الی ۳ خطی درباره مضمون محتوا
postDescription: "دنیای قبل و بعد از دیپ لرنینگ در دنیای کامپیوتر ویژن را بررسی کنید  و تفاوت‌هایی که در آن‌ها وجود دارد را بررسی کنید. این توییت تجربی نوشته شده است."

##### لینک محتوا
postLink: "https://twitter.com/HesamSalehian/status/1505996698945945603"

**Comment by Hameds** [comment]
ضمن تشکر، من لینک رو اصلاح و کوئری استرینگ اضافه رو برمی‌دارم
