### ISSUE TITLE
اسنپ شات گرفتن از یک سایت با تمامی دپندنسی های آن

### ISSUE THREAD

**Issue by shabane** [softwaretalks/newsletter#458]
##### نام و نام‌خانوادگی شما
userFullName: "آریا شبانه"

##### عنوان محتوا
postTitle: "اسنپ شات گرفتن از یک سایت با تمامی دپندنسی های آن"

##### خلاصه‌ای حداکثر ۲ الی ۳ خطی درباره مضمون محتوا
postDescription: "ما روزانه محتوای زیادی از سایت های مختلفی می‌خوانیم. برخی از این محتوا را ممکن است فراموش کنیم و یا به دلایلی مثل اجبار سانسور چی اون محتوا از سایت منبع پاک شود. در چنین مواقعی می‌توانیم با کلون کردن اون صفحه سایت، محتوا را افلاین در دسترس داشته باشیم."

##### لینک محتوا
postLink: "https://bit-orbit.github.io/blog/post/web-snapshout/"

**Comment by amirshnll** [comment]
@shabane 

لطفا اسم و فامیلتون رو فارسی وارد کنید و در عنوان issue هم عنوان فارسی مقاله را قرار دهید

**Comment by shabane** [comment]
> @shabane
> 
> لطفا اسم و فامیلتون رو فارسی وارد کنید و در عنوان issue هم عنوان فارسی مقاله را قرار دهید

سلام. عذر می‌خواهم. اصلاح شد.
