### ISSUE TITLE
اضافه کردن لوگوی پاکت برای شماره یک

### ISSUE THREAD

**Issue by Hameds** [softwaretalks/newsletter#46]
![pakat-new-logo-2](https://user-images.githubusercontent.com/1385656/103536798-69b6ec00-4ea8-11eb-8d58-f86a4d705a37.png)
![Screenshot 2021-01-02 182055](https://user-images.githubusercontent.com/1385656/103536806-6c194600-4ea8-11eb-832d-fe0169be6320.png)

**Comment by amirbagh75** [comment]
سلام. قرار شد ترجیحا ساده و بدون عکس باشه همه چیز. نیازه حتما عکس اضافه بشه؟

**Comment by amirbagh75** [comment]
<div dir='rtl'>
من فرداشب موضوع issue #35 رو که پیاده میکنم عملا این هم داخلش حل شده است. چون با فرمت html میتونیم عکس رو هم قرار بدیم و src رو از هاست‌ عکس‌های پاکت استفاده کنیم.
</div>

**Comment by amirbagh75** [comment]
https://pakat.net/wp-content/uploads/2020/02/pakat-new-logo-white_00ea005b1_2512.png

**Comment by amirbagh75** [comment]
![image](https://user-images.githubusercontent.com/21690865/103621485-84da3800-4f4a-11eb-883c-6bff2ab00a9b.png)
Done
