### ISSUE TITLE
چرا از گوگل فونت باید در وبسایت خود استفاده کنید

### ISSUE THREAD

**Issue by amirshnll** [softwaretalks/newsletter#476]
##### نام و نام‌خانوادگی شما
userFullName: "امیر شکری"

##### عنوان محتوا
postTitle: "چرا از گوگل فونت باید در وبسایت خود استفاده کنید"

##### خلاصه‌ای حداکثر ۲ الی ۳ خطی درباره مضمون محتوا
postDescription: "احتمالا در پروژه های مختلف خودتون مخصوصا با اومدن فونت وزیر به گوگل فونت از این سرویس استفاده کرده اید ولی شاید براتون سوال پیش بیاد اصلا مزیت ها و معایبی که استفاده از گوگل فونت داره چیه اگر دنبال این موارد هستید این تاپیک کورا به سوالتون پاسخ میده"

##### لینک محتوا
postLink: "https://www.quora.com/Why-use-Google-Fonts-What-are-the-advantages-and-disadvantages-of-using-Google-Fonts"

**Comment by Hameds** [comment]
ضمن تشکر بابت لینک، نمی‌دونم قبلاً‌ از سایت‌های پرسش و پاسخ محتوا داشتیم یا خیر؟ اما به صورت کلی فکر می‌کنم باید از این مساله اجتناب کنیم (مربوط به این پرسش خاص نیست) مایلم نظر شما رو هم در این مورد بدونم @amirshnll

**Comment by amirshnll** [comment]
@Hameds 


مرسی حامد عزیز نظر نهایی در مورد سیاست خبرنامه با شماست اما تاپیک های کورا اون هایی که پاسخ های مناسبی دارند و سوالات و بحث های اسپم نیستند به نظرم تفاوتی با یه بلاگ پست معمولی ندارند روی هم بلاگ پست ها و تاپیک های سوال و جواب وقتی محتوا ارائه بشه به عنوان لینک های ارزشمند برای خبرنامه به نظر مفید بیاد به همین دلیل این مورد رو ثبت کردم البته میتونیم جایگزین این لینک لینک های مشابه از سایت های دیگه بزاریم اگر  هم نه کلا issue رو ببند
ارادت

**Comment by Hameds** [comment]
@amirshnll 
اگر محتوایی در یک سایت پرسش و پاسخ، پختگی و عمق لازم رو داره چرا که نه؟ ممنونم بابت توضیحات.
