### ISSUE TITLE
به عنوان برنامه‌نویس به فکر سلامتی‌تون هستین؟!

### ISSUE THREAD

**Issue by amirbagh75** [softwaretalks/newsletter#49]
##### نام و نام‌خانوادگی شما
userFullName: "امیرحسین بقایی"

##### لینک مطلب رو کامل وارد کنید.
postLink: "https://hamed.blog/healthy-programmer/"

##### عنوان مطلب (یا یک عنوان اختیاری بنویسید یا هم عنوان خود مقاله رو کپی کنید)
postTitle: "به عنوان برنامه‌نویس، حواستون به سلامتی‌تون هست؟ (جسمی)"

##### خلاصه‌ای حداکثر ۲ الی ۳ خطی درباره محتوای مقاله بنویسید.
postDescription: "تا وقتی سلامتی از دست نرفته باشه نمیشه ارزشش رو فهمید، پس به عنوان یک برنامه‌نویس که دائم پشت میز هستیم و زل زدیم به مانیتور باید حواسمون به سلامتیمون باشه تا بتونیم تا آخر عمرمون با لذت و اشتیاق همچنان به خلق کردن مشغول باشیم. حامد سعیدی توی وبلاگش خیلی خلاصه و ساده گفته که حواسمون باید به چه‌ چیزهایی جمع باشه. "

**Comment by Hameds** [comment]
<div dir='rtl'>

@amirbagh75 ممنون که این مطلب رو انتخاب کردی. فعلاً برای این شماره به ۲ دلیل برچسب رو برداشتم

- تصاویر نوشته‌های قدیمی از جمله این نوشتته مشکل دارند
- نمی‌خوام در شماره‌های اول به نظر بیاد از خبرنامه برای پروموت کردن محتوای مرتبط با سازندگانش استفاده شده


</div>

**Comment by amirbagh75** [comment]
به نظرم الان شاید بد نباشه این موضوع رو توی خبرنامه اضافه کنیم
@Hameds

**Comment by Hameds** [comment]
@amirbagh75 این شماره مطالب زیادی داره. صبر کنیم اگر در شماره‌ای مطلب کم بود این رو اضافه می‌کنیم. ممنونم از لطف شما
