### ISSUE TITLE
حل مشکلات شبکه کوبرنتیز به شیوه گیتهاب

### ISSUE THREAD

**Issue by ohmydevops** [softwaretalks/newsletter#496]
##### نام و نام‌خانوادگی شما
userFullName: "امیرحسین بقایی"

##### عنوان محتوا
postTitle: "حل مشکلات شبکه کوبرنتیز به شیوه گیتهاب"

##### خلاصه‌ای حداکثر ۲ الی ۳ خطی درباره مضمون محتوا
postDescription: "در این مطلب، تیم فنی گیتهاب توضیح میده چطوری یک مشکل latency در شبکه پیچیده کوبرنتیز رو حل کردن و مرحله به مرحله و با ساده‌سازی مسائل پیش رفتند."

##### لینک محتوا
postLink: "https://github.blog/2019-11-21-debugging-network-stalls-on-kubernetes/"

**Comment by Hameds** [comment]
@ohmydevops این یک توضیح لازم داره امیر جان. اگر فرصت داشتی قبل خبرنامه هفته آینده یک توضیح درباره‌اش بنویس

**Comment by ohmydevops** [comment]
بله اضافه کردم

**Comment by Hameds** [comment]
> بله اضافه کردم

ممنون امیر جان. فکر کنم اشتباهی جای لینک قرار گرفت @ohmydevops

**Comment by ohmydevops** [comment]
بله اشتباه کردم. اصلاح شد
