### ISSUE TITLE
راه‌حل دسترسی به اینترنت برای برنامه‌نویسان

### ISSUE THREAD

**Issue by ohmydevops** [softwaretalks/newsletter#511]
##### نام و نام‌خانوادگی شما
userFullName: "امیرحسین بقایی"

##### عنوان محتوا
postTitle: "راه‌حل دسترسی به اینترنت برای برنامه‌نویسان"

##### خلاصه‌ای حداکثر ۲ الی ۳ خطی درباره مضمون محتوا
postDescription: "اگر برنامه‌نویس هستید و قصد دارید در روز کمتر به وضعیت اینترنت ناسزا بدید، راه‌اندازی یک VPN یا Proxy میتونه راه‌حل شما باشه. پروتکل‌ها و ابزارهای مختلفی وجود داره ولی این روزها استفاده از V2ray شاید راه‌حل خوبی باشه. در این مخزن گیتهاب، راه‌حل ساده‌ای برای دپلوی و نصب این ابزار ارائه شده است."

##### لینک محتوا
postLink: "https://github.com/miladrahimi/v2ray-docker-compose"

**Comment by ohmydevops** [comment]
این رو خودمم مطمئن نیستم که جاش تو خبرنامه‌ هستش یا نه

**Comment by Hameds** [comment]
> این رو خودمم مطمئن نیستم که جاش تو خبرنامه‌ هستش یا نه @Hameds @amirshnll

در شرایط فعلی، حتما برای عده‌ای مفید خواهد بود
