### ISSUE TITLE
گیت‌هاب دوباره به صورت کامل برای ایران در دسترس است

### ISSUE THREAD

**Issue by Hameds** [softwaretalks/newsletter#52]
##### نام و نام‌خانوادگی شما
userFullName: "حامد سعیدی"

##### لینک مطلب رو کامل وارد کنید.
postLink: "https://github.blog/2021-01-05-advancing-developer-freedom-github-is-fully-available-in-iran/"

##### عنوان مطلب (یا یک عنوان اختیاری بنویسید یا هم عنوان خود مقاله رو کپی کنید)
postTitle: "گیت‌هاب دوباره به صورت کامل برای ایران در دسترس است"

##### خلاصه‌ای حداکثر ۲ الی ۳ خطی درباره محتوای مقاله بنویسید.
postDescription: "بعد از آنکه در اواسط سال ۲۰۱۹ گیت‌هاب ارائه بخشی عمده‌ای از خدمات خود را به ایران متوقف و حساب کاربری برنامه‌نویسان ایرانی را محدود کرد، ۵ ژانویه ۲۰۲۱ مدیرعامل گیت‌هاب در پست وبلاگی خبر در دسترس قرار گرفتن همه گیت‌هاب برای ایران را اعلام کرد. گیت‌هاب اعلام کرد که ۲ سال پیگیر دریافت مجوز از دولت ایالات متحده بوده تا دوباره خدماتش را برقرار کند و به زودی برای سایر کشورهای تحریم شده نظیر سوریه و کریمه هم این خدمات به صورت کامل در دسترس قرار خواهند گرفت"

**Comment by amirbagh75** [comment]
توی محتوا بخش لینک و تایتل برعکس نوشته شده که با اجازه به صورت دستی ویرایش میکنم. توی نسخه تست متوجه این اشکال شدم.
