### ISSUE TITLE
مروری بر ارث‌بری در جاوا با دو مثال

### ISSUE THREAD

**Issue by asadise** [softwaretalks/newsletter#54]
##### نام و نام‌خانوادگی شما
userFullName: "مرتضی اسدی"

##### لینک مطلب رو کامل وارد کنید.
postLink: "http://asadiweb.ir/%D8%A7%D8%B1%D8%AB-%D8%A8%D8%B1%DB%8C-%D8%AF%D8%B1-%D8%AC%D8%A7%D9%88%D8%A7/"

##### عنوان مطلب (یا یک عنوان اختیاری بنویسید یا هم عنوان خود مقاله رو کپی کنید)
postTitle: "مروری بر ارث‌بری در جاوا با دو مثال"

##### خلاصه‌ای حداکثر ۲ الی ۳ خطی درباره محتوای مقاله بنویسید.
postDescription: "ارث بری (inheritance) یک مفهوم بنیادی و کلیدی در برنامه‌نویسی شی‌گرا است.در برنامه‌نویسی نیز این واژه مفهومی مشابه دنیای واقعی دارد و به معنای ارث بردن خصوصیات است. در این نوشته قصد دارم نگاهی دوباره به ارث‌بری در جاوا داشته باشم. در ادامه به دو سوال درخصوص ارث‌بری در جاوا پاسخ دهید و توانمندی خود را محک بزنید!"

**Comment by Hameds** [comment]
<div dir='rtl'>

فکر می‌کنم عنوان خیلی طولانی باشد. در صورت امکان عنوان کوتاه‌تری را انتخاب کنید.

</div>

**Comment by Hameds** [comment]
<div dir="rtl">

ممنونم که عنوان رو کوتاه کردید، من لینک رو چک کردم ظاهرا با کلیک بر روی لینک‌های روی صفحه (مثلاً منوی بالا) صفحات پاپ آپ تبلیغاتی باز می‌شه. ممکنه پیش از اینکه برای ارسال در خبرنامه تایید بشه این مورد رو هم چک بفرمایید؟

</div>

**Comment by asadise** [comment]
ظاهرا برای مرورگرهای دسکتاپ این مشکل وجود داشت... به هر روی اصلاح شد.
