### ISSUE TITLE
اصولی ساده و بدیهی برای کد‌های آدمیزادی در PHP!

### ISSUE THREAD

**Issue by amirbagh75** [softwaretalks/newsletter#62]
##### نام و نام‌خانوادگی شما
userFullName: "امیرحسین بقایی"

##### عنوان مطلب (یا یک عنوان اختیاری بنویسید یا هم عنوان خود مقاله رو کپی کنید)
postTitle: "اصولی ساده و گاها بدیهی برای کد‌های آدمیزادی در PHP!"

##### خلاصه‌ای حداکثر ۲ الی ۳ خطی درباره محتوای مقاله بنویسید.
postDescription: "نوشتن کد تمیز، خوانا و قابل توسعه مهارتیه که به مرور و با تمرین زیاد و مطالعه بدست میاد. اگر شما هم از این دسته برنامه‌نویسان هستید که قصد دارند کد تمیز بنویسند و از قضا PHP هم کار میکنید، پس این ریپوزیتوری Clean code in php رو حتما باید ‌ یک نگاهی بندازین. "

##### لینک مطلب رو کامل وارد کنید.
postLink: "https://github.com/jupeter/clean-code-php"

**Comment by amirshnll** [comment]
@amirbagh75

<br />
من این رو ترجمه کردم و زیر پروژش نسخه ی فارسیش اضافه شده اگر حوصله داشتی یه نگاه بنداز مشکلی دیدی حتما اصلاح کنیم. 
<br />
نسخه فارسی : 
<br />
https://github.com/amirshnll/clean-code-php
<br />
نسخه اصلی هم زیرش بری فارسی رو اضافه کردن
🦾

**Comment by amirbagh75** [comment]
به به چه عالی.
آره حتما در اولین فرصت بررسی میکنم فردا یا پس‌فردا
شاید بد نباشه برای این هفته توی محتوای خبرنامه‌هم اضافه‌اش کنی
