### ISSUE TITLE
واژه ی نامه ی کاملی از اصطلاحات جلسه های حرفه ای بخوانید

### ISSUE THREAD

**Issue by amirshnll** [softwaretalks/newsletter#67]
##### نام و نام‌خانوادگی شما
userFullName: "Amir Shokri"

##### عنوان مطلب (یا یک عنوان اختیاری بنویسید یا هم عنوان خود مقاله رو کپی کنید)
postTitle: "واژه نامه کاملی از اصطلاحات جلسه‌های حرفه‌ای بخوانید"

##### خلاصه‌ای حداکثر ۲ الی ۳ خطی درباره محتوای مقاله بنویسید.
postDescription: "یکی از مواردی که قبل از جلسات مخصوصا جلسات بین المللی باید بدانید اصطلاحات و کلمات اختصاری هست که دونستن اونها باعث میشه تا حد قابل قبولی بتونید با محیط آشنا باشید اگر بار اولتون هست که توی یه جلسه ی تیمی خارجی می خواید شرکت کنید احتمالا خیلی بدردتون میخوره؛ البته تیم های خفن ایرانی هم از این اصطلاحات بی بهره نیستن"

##### لینک مطلب رو کامل وارد کنید.
postLink: "https://www.lucidmeetings.com/glossary"

**Comment by Hameds** [comment]
@amirshnll ممنونم. فاصله بین کلمات در عنوان رو اصلاح کردم
