### ISSUE TITLE
اضافه کردن لاگ های کاربردی برای ارسال ایمیل در پروداکشن

### ISSUE THREAD

**Issue by amirbagh75** [softwaretalks/newsletter#68]
<div dir='rtl'>
در هنگام ارسال ایمیل در نسخه پروداکشن، لاگ‌های بیشتری نوشته شود تا در صورت مشکل بتوانیم بفهمیم چی شده!
همچنین مجدد rate limit ها  و محدودیت‌های SendInBlue مطالعه شود و در صورت نیاز تغییرات اعمال شود. (البته باید مطمئن بشیم که پاکت رفتارش با sendinblue تفاوتی نداشته باشه)
</div>

**Comment by Hameds** [comment]
<div dir='rtl'>

فکر می‌کنم باید به تدریج به جای استفاده از `SMTP` در loop از ایجاد کمپین استفاده کنیم. API امکان ایجاد کمپین جدید رو داره. نمونه دستی ایجاد شده کمپین رو در پنل پاکت می‌تونی ببینی: ‍‍‍`SoftwareTalks #2` حتی احتمالاً بشه از روی خروجی html آرشیو خبرنامه، با API یک کمپین در پنل پاکت ساخت. نیازمند بررسی بیشتره

</div>

**Comment by amirbagh75** [comment]
امروز بررسی میکنم که اگر شد راه‌حل بهتر رو استفاده کنیم.

**Comment by amirbagh75** [comment]
چه قدر این قابلیتش جالبه. آمار خوبی هم میده

**Comment by amirbagh75** [comment]
اینو امروز مطالعه  و بررسی میکنم و ساختار ارسال ایمیل رو کلن میبرم روی کمپین‌ها
https://help.sendinblue.com/hc/en-us/articles/209587285--Creating-an-email-campaign

**Comment by amirbagh75** [comment]
ایشوی جدیدی برای این موضوع ایجاد میکنم
