### ISSUE TITLE
سایت اصلی خبرنامه‌

### ISSUE THREAD

**Issue by amirbagh75** [softwaretalks/newsletter#7]
<div dir='rtl'>

- روی گیتهاب‌پیج هاست میشود
- درباره پروژه و اهدافش توضیحاتی داخل سایت قرار میگیره
- درباره نحوه مشارکت در تهیه محتوای هفتگی توضیحاتی داخل سایت قرار میگیره.
- به صفحه ثبت‌نام لینک داده شود. (یا این که ثبت نام داخل خود همین سایت صورت گیرد)
- نمایش لیست آرشیو‌های گذشته

</div>

**Comment by Hameds** [comment]
این اولین و مهم‌ترین بخش پروژه است. بعد از اجرای سایت تازه می‌توان درباره بقیه موارد کار کرد

**Comment by amirbagh75** [comment]
من این قالب رو پیدا کردم و میتونیم متناسب با لایسنسی که داره برای صفحه اصلی پروژه استفاده کنیم.
همچنین خیلی راحت میشه محتواهای مختلفی رو هم داخلش قرار داد مثل آرشیو‌ خبرنامه‌های ارسال شده و آموزش مشارکت (متن و ویدیو) و متن درباره پروژه و ...
من نسخه rtl و ترتمیزشو تا فردا ارسال میکنم اینجا.

**Comment by amirbagh75** [comment]
امکانش هست لوگوی جلسات باز رو برام جایی ارسال کنید؟ @Hameds 
لوگویی که به جای ST نوشته باشه SN. اگر هم فکر میکنید میشه رنگش رو از نارنجی به رنگ دیگه‌ای عوض کرد.

**Comment by Hameds** [comment]
> امکانش هست لوگوی جلسات باز رو برام جایی ارسال کنید؟ @Hameds
> لوگویی که به جای ST نوشته باشه SN. اگر هم فکر میکنید میشه رنگش رو از نارنجی به رنگ دیگه‌ای عوض کرد.

https://github.com/softwaretalks/design

**Comment by amirbagh75** [comment]
صفحه ثبت‌نام رو اگر ممکنه لینکی چیزی ازش بدید منم ببینم ساختارشو. من از توی سایت دکمه ثبت‌نام‌مون رو بهش لینک میکنم.
