### ISSUE TITLE
قوانین مشارکت و استفاده

### ISSUE THREAD

**Issue by LordArma** [softwaretalks/newsletter#73]
سلام. با تشکر از ایده خوبتون.

می‌خواستم بپرسم آیا قوانین و شرایط استفاده و مشارکت موجوده؟

به عنوان مثال چندین سؤال در همین ابتدا برام پیش اومده:

هر کسی چند تا مطلب می‌تونه بفرسته؟
آیا لابیگری مجازه؟ من می‌تونم ایشو رو برای دوستامبفرستم تا لایک بزنن و بالا بیاد؟
ممکنه مطلبی بالا بیاد ولی توسط گرداننده حذف بشه و دیده نشه؟
آیا باید نویسنده مطلب خودش ایشو رو ثبت کنه و یا میشه مطالب دیگران رو هم ایشو کرد؟
سرنوشت لینک‌های تکراری چی میشه؟
آیا فقط زبان فارسی مجازی یا میشه به سایر زبان‌ها مثل انگلیسی و گیلکی هم مطلب درج کرد؟

پرسش‌ها البته خیلی بیشترن صرفاً به چند تاشون اشاره کردم 🙏🏻

**Comment by Hameds** [comment]
<div dir='rtl'>

سلام. ممنون از توجه شما

هنوز قوانین نوشته نشده اما خوشحال می‌شم سوالات شما رو پاسخ بدم:

- محدودیتی در ارسال مطلب نیست ولی در هر شماره خبرنامه تعداد محدودی از محتوای موجود ارسال می‌شه
- لایک کردن مطالب در حال حاضر تاثیر مستقیمی روی قرار گرفتن یک مطلب در خبرنامه نداره و البته روی گیت‌هاب ما ابزاری برای تشخیص اینکه یک پست تحت چه شرایطی در حال گرفتن لایک است نداریم
- بلی ولی شرایطش رو در قوانین اعلام می‌کنیم
- هم مطالب خودتون و هم مطالب دیگران ولی در هر شماره بیش از یک مطلب نوشته مرتبط با یک فرد ارسال نخواهد شد تا خبرنامه به محل پروموت کردن محتوای یک فرد مشخص تبدیل نشه
- اگر یادمون بمونه اجازه انتشار لینک تکراری نمی‌دیم شاید در آینده این مساله اتوماتیک کنترل بشه
- زبان فارسی و انگلیسی که طبیعی است. در مورد زبان‌های دیگر نظری ندارم و دلیلی برای نبودنش نمی‌بینم

</div>

**Comment by amirbagh75** [comment]
فکر میکنم نیازه بخش قوانین رو هم دستی به سر و روش بکشیم. این باگ‌های اخیر رو رفع کنم روی این موضوع و سرجمع کردن قوانین کاربردی وقت میزارم

**Comment by amirbagh75** [comment]
من این هفته سعی میکنم این موضوع قوانین رو به کمک شما به یک جای خوبی برسونم @Hameds
