### ISSUE TITLE
افزودن فایل README.md

### ISSUE THREAD

**Issue by mskf1383** [softwaretalks/newsletter#80]
<div dir="rtl">

سلام.
حتما یه فایل README.md به پروژه اضافه کنید. چون افرادی که تازه وارد می‌شن نمی‌تونن به خوبی متوجه بشن پروژه چی هست.
فایل README.md توی صفحه اول نمایش داده میشه و می‌تونید اطلاعات پروژه و خیلی چیزهای دیگه رو اونجا بنویسید.
در ضمن باید در قالب Markdown بنویسید که اگر جستجو کنید کلی راهنما براش وجود داره.
موفق باشید
</div>

**Comment by amirbagh75** [comment]
سلام. ممنون از پیشنهادت. درست میگی. البته در حقیقت این ریپو چیز خیلی خاصی نداره و بیشتر مطالب رو توی خود سایت که توی ریپو لینک هم براش گذاشتیم، قرار دادیم. اکثر افراد از اونجا وارد اینجا میشن. ولی در هر صورت باید یک Readme بنویسیم.
