### ISSUE TITLE
۵۰+۲ نکته کاربردی برای همه دولوپر ها

### ISSUE THREAD

**Issue by arianomrani** [softwaretalks/newsletter#85]
##### نام و نام‌خانوادگی شما
userFullName: "آریان عمرانی"

##### عنوان مطلب (یا یک عنوان اختیاری بنویسید یا هم عنوان خود مقاله رو کپی کنید)
postTitle: "۵۰+۲ نکته کاربردی برای همه دولوپر ها"

##### خلاصه‌ای حداکثر ۲ الی ۳ خطی درباره محتوای مقاله بنویسید.
postDescription: "گاهی وقتا یک جمله می تونه کمک بزرگی تو کار باشه یا یک نقل قول مسیر روبه رو رو بهتر به ما نشون بده حالا می خواد تازه کار باشی یا کلی تجربه داشته باشی.
"

##### لینک مطلب رو کامل وارد کنید.
postLink: "https://devdon.ir/52-essential-tips-for-developer/"

**Comment by Hameds** [comment]
@arianomrani متاسفانه لینک شما کار نمی‌کند

**Comment by Hameds** [comment]
@arianomrani ضمن تشکر از شما، مطلب مشاهده شد. فعلاً به گمان من از نظر کیفی این مطلب برای مخاطبین این خبرنامه مناسب نیست اما مطالب دیگری در همان سایت آمده که امکان قرارگیری در محتوای خبرنامه را دارند. مشتاق دیدن مطالب بعدی پیشنهادی شما هستیم. ارادتمند
