### ISSUE TITLE
 چجوری روی یک سرور، چند سرویس مختلف رو با استفاده از Nginx و Docker، مستقر کنیم؟

### ISSUE THREAD

**Issue by alinaseri07** [softwaretalks/newsletter#86]
##### نام و نام‌خانوادگی شما
userFullName: "علی ناصری"

##### عنوان مطلب (یا یک عنوان اختیاری بنویسید یا هم عنوان خود مقاله رو کپی کنید)
postTitle: " چجوری روی یک سرور، چند سرویس مختلف رو با استفاده از Nginx و Docker، مستقر کنیم؟"

##### خلاصه‌ای حداکثر ۲ الی ۳ خطی درباره محتوای مقاله بنویسید.
postDescription: "اگه براتون سوال شده چجوری چند تا دامین به یک سرور وصل میشه و مدیریتشون با Docker چجوری انجام میشه، تو این مقاله قراره بهش بپردازیم"

##### لینک مطلب رو کامل وارد کنید.
postLink: "https://vrgl.ir/dRg5S"

**Comment by amirbagh75** [comment]
<div dir='rtl'>

ممنون علی عزیز
فقط من فکر میکنم تیتر رو این شکلی بنویسیم خواندنش راحت‌تر میشه:
چجوری چندین سرویس مختلف با استفاده از Nginx و Docker روی یک سرور مستقر کنیم

</div>

**Comment by alinaseri07** [comment]
عالیه. کاملا موافقم. مرسی از پیشنهادت

**Comment by amirbagh75** [comment]
قربانت. دستت درد نکنه علی عزیز
