### ISSUE TITLE
نحوه قرارداد نوشتن برای پروژه های برنامه نویسی

### ISSUE THREAD

**Issue by AmiirAbM** [softwaretalks/newsletter#88]
##### نام و نام‌خانوادگی شما
userFullName: "امیر ابوئی"

##### عنوان مطلب (یا یک عنوان اختیاری بنویسید یا هم عنوان خود مقاله رو کپی کنید)
postTitle: "نحوه قرارداد نوشتن برای پروژه های برنامه نویسی"

##### خلاصه‌ای حداکثر ۲ الی ۳ خطی درباره محتوای مقاله بنویسید.
postDescription: "در این پست ویرگول راجع به قرارداد توی پروژه های برنامه نویسی صحبت میشه، چیزی که بیشتر بچه های فریلنسر این حوزه باهاش سر و کار دارن و نکات مهمی که در تنظیم یک پروژه باید رعایت بشه رو بررسی کرده"

##### لینک مطلب رو کامل وارد کنید.
postLink: "https://vrgl.ir/oYFDb"

**Comment by amirbagh75** [comment]
ممنون از مشارکت شما
ترجیح خبرنامه بر اینه که همه چیز فارسی باشه. اگر ممکنه اسم‌تون رو فارسی ویرایش کنید عالی میشه

**Comment by Amiraidev** [comment]
> ممنون از مشارکت شما
> ترجیح خبرنامه بر اینه که همه چیز فارسی باشه. اگر ممکنه اسم‌تون رو فارسی ویرایش کنید عالی میشه

ویرایش اسم انجام شد :)

**Comment by amirbagh75** [comment]
متشکرم
