### ISSUE TITLE
آموزش نصب داپلیکیتور(بسته آسان نصب دموها) روی وردپرس

### ISSUE THREAD

**Issue by AmiirAbM** [softwaretalks/newsletter#89]
##### نام و نام‌خانوادگی شما
userFullName: "امیر ابوئی"

##### عنوان مطلب (یا یک عنوان اختیاری بنویسید یا هم عنوان خود مقاله رو کپی کنید)
postTitle: "آموزش نصب داپلیکیتور(بسته آسان نصب دموها) روی وردپرس"

##### خلاصه‌ای حداکثر ۲ الی ۳ خطی درباره محتوای مقاله بنویسید.
postDescription: "قالب های وردپرسی که گاهی خریداری میکنید، دارای بسته آسان نصب هستند که دموهای قالب را عیناً روی سایت شما پیاه سازی میکنند. بسته آسان نصب تشکیل شده از وردپرس، قالب خریدرای شده و محتوا فارسی دمو مد نظر شما که در چهار مرحله میتوانید آن را نصب و راه اندازی کنید."

##### لینک مطلب رو کامل وارد کنید.
postLink: "https://www.emiato.com/installation-of-duplicator-package/"

**Comment by Hameds** [comment]
https://github.com/softwaretalks/newsletter/issues/90#issuecomment-781063499
