### ISSUE TITLE
آموزش ترفند ریسپانسیو سازی قالب وردپرس انفولد

### ISSUE THREAD

**Issue by AmiirAbM** [softwaretalks/newsletter#90]
##### نام و نام‌خانوادگی شما
userFullName: "امیر ابوئی"

##### عنوان مطلب (یا یک عنوان اختیاری بنویسید یا هم عنوان خود مقاله رو کپی کنید)
postTitle: "آموزش ترفند ریسپانسیو سازی قالب وردپرس انفولد"

##### خلاصه‌ای حداکثر ۲ الی ۳ خطی درباره محتوای مقاله بنویسید.
postDescription: "در این آموزش پدر انفولد ایران قصد داره یکی از ترفندهای مهم و کاربردی را برای بهبود نمایش آیتم ها و عناصر مختلف استفاده شده در صفحه ساز اختصاصی قالب انفولد را به شما آموزش بده. ریسپانسیوسازی قالب که امروزه جزو یکی از ضروری ترین ویژگی های یک سایت هستش بدون هیچ افزونه اضافه تری به شما آموزش داده میشه!

##### لینک مطلب رو کامل وارد کنید.
postLink: "https://www.emiato.com/enfold-theme-responsive/"

**Comment by Hameds** [comment]
@AmiirAbM پدر انفولد ایران؟

**Comment by AmiirAbM** [comment]
بله

**Comment by Hameds** [comment]
ممنون از مشارکت شما. صحت‌سنجی القابی نظیر «پدر [نام تکنولوژی یا کتابخانه یا بسته نرم‌افزاری] ایران» متاسفانه از ما ساخته نیست. از طرفی محتوای وارد شده مربوط به سایتی است که مستقیماً محصولات و خدماتی برای فروش دارد. محتوایی که برای سئو یا توسعه کسب و کارها نوشته می‌شوند مناسب مخاطبین این خبرنامه نیستند (در تلاشیم تا محل تبلیغات برای کسب و کارها نباشیم).
