### ISSUE TITLE
تفاوت بین دیتاآنالیست و دیتاساینتیست

### ISSUE THREAD

**Issue by amirshnll** [softwaretalks/newsletter#93]
##### نام و نام‌خانوادگی شما
userFullName: "امیر شکری"

##### عنوان مطلب (یا یک عنوان اختیاری بنویسید یا هم عنوان خود مقاله رو کپی کنید)
postTitle: "تفاوت بین دیتاآنالیست و دیتاساینتیست"

##### خلاصه‌ای حداکثر ۲ الی ۳ خطی درباره محتوای مقاله بنویسید.
postDescription: "شاید اولش حس کنید دیتاآنالیست و دیتاساینتیست تفاوت زیادی ندارن چون در نهایت قراره با داده ها کار کنن ولی در واقع تفاوت های زیادی هم از نظر دانش مورد نیاز دارن و هم جایگاه های شغلی متفاوتی دارن یکم بیشتر بخونید اطلاعات جالبی رو کشف می کنید"

##### لینک مطلب رو کامل وارد کنید.
postLink: "https://algorithmia.com/blog/data-analyst-vs-data-scientist-whats-the-difference-algorithmia-blog"

**Comment by amirbagh75** [comment]
سلام.
ممنونم از مشارکتت
ترجیح بر اینه که توضیحات و تیتر مطلب فارسی باشه. اگر برات مقدوره که فارسی بکنیشون عالی میشه ولی خب انگلیسی هم در نهایت مشکلی نداره.

**Comment by amirshnll** [comment]
@amirbagh75 
اصلاح شد

**Comment by amirbagh75** [comment]
عالی. فقط اسمت هم هنوز انگلیسی نوشته شده 😅

**Comment by amirshnll** [comment]
@amirbagh75
طبق عادت بود اصلاح شد

**Comment by amirbagh75** [comment]
خیلی هم عالی شد. ممنونم ازت
